// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.danjjohnson.compress_video

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is CompressVideoError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class CompressVideoError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * The wire-format media info message returned by [ProbeHostApi.getMediaInfo].
 *
 * This is the generated, private counterpart of the public, hand-written `MediaInfo`
 * class in `lib/src/media_info.dart` — see that file for the documented public API.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MediaInfoMessage (
  /** Duration of the media, in milliseconds. */
  val durationMs: Long,
  /** Displayed (rotation-corrected) width, in pixels. Never the coded, pre-rotation width. */
  val widthPx: Long,
  /** Displayed (rotation-corrected) height, in pixels. Never the coded, pre-rotation height. */
  val heightPx: Long,
  /**
   * Unsigned clockwise rotation, in degrees, as reported by the platform before the
   * correction that produced [widthPx]/[heightPx] was applied. `0` for an unrotated clip.
   */
  val rotationDegrees: Long,
  /** Size of the underlying file, in bytes. */
  val sizeBytes: Long,
  /**
   * Normalised video codec token (`h264`, `hevc`, `av1`, `vp9`, `unknown`), or `null` when
   * the platform could not determine it. `null` is the sentinel for unknown — never an
   * empty string.
   */
  val videoCodec: String? = null,
  /**
   * Average video-track bitrate, in bits per second, or `null` when the platform could not
   * determine it. `null` is the sentinel for unknown — never `0`.
   */
  val videoBitrateBps: Long? = null,
  /**
   * Video frame rate, in frames per second, or `null` when the platform could not determine
   * it. `null` is the sentinel for unknown — never `0`. Never rounded to an integer.
   */
  val frameRateFps: Double? = null,
  /** Whether the media has at least one audio track. */
  val hasAudio: Boolean,
  /**
   * Whether the video is HDR (PQ or HLG transfer characteristic). `false` when the running
   * platform cannot determine HDR status — never an exception.
   */
  val isHdr: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaInfoMessage {
      val durationMs = pigeonVar_list[0] as Long
      val widthPx = pigeonVar_list[1] as Long
      val heightPx = pigeonVar_list[2] as Long
      val rotationDegrees = pigeonVar_list[3] as Long
      val sizeBytes = pigeonVar_list[4] as Long
      val videoCodec = pigeonVar_list[5] as String?
      val videoBitrateBps = pigeonVar_list[6] as Long?
      val frameRateFps = pigeonVar_list[7] as Double?
      val hasAudio = pigeonVar_list[8] as Boolean
      val isHdr = pigeonVar_list[9] as Boolean
      return MediaInfoMessage(durationMs, widthPx, heightPx, rotationDegrees, sizeBytes, videoCodec, videoBitrateBps, frameRateFps, hasAudio, isHdr)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      durationMs,
      widthPx,
      heightPx,
      rotationDegrees,
      sizeBytes,
      videoCodec,
      videoBitrateBps,
      frameRateFps,
      hasAudio,
      isHdr,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MediaInfoMessage
    return MessagesPigeonUtils.deepEquals(this.durationMs, other.durationMs) && MessagesPigeonUtils.deepEquals(this.widthPx, other.widthPx) && MessagesPigeonUtils.deepEquals(this.heightPx, other.heightPx) && MessagesPigeonUtils.deepEquals(this.rotationDegrees, other.rotationDegrees) && MessagesPigeonUtils.deepEquals(this.sizeBytes, other.sizeBytes) && MessagesPigeonUtils.deepEquals(this.videoCodec, other.videoCodec) && MessagesPigeonUtils.deepEquals(this.videoBitrateBps, other.videoBitrateBps) && MessagesPigeonUtils.deepEquals(this.frameRateFps, other.frameRateFps) && MessagesPigeonUtils.deepEquals(this.hasAudio, other.hasAudio) && MessagesPigeonUtils.deepEquals(this.isHdr, other.isHdr)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.widthPx)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.heightPx)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rotationDegrees)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sizeBytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.videoCodec)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.videoBitrateBps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.frameRateFps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hasAudio)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isHdr)
    return result
  }
  override fun toString(): String {
    return "MediaInfoMessage(durationMs=$durationMs, widthPx=$widthPx, heightPx=$heightPx, rotationDegrees=$rotationDegrees, sizeBytes=$sizeBytes, videoCodec=$videoCodec, videoBitrateBps=$videoBitrateBps, frameRateFps=$frameRateFps, hasAudio=$hasAudio, isHdr=$isHdr)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaInfoMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is MediaInfoMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Reads media info from a file. Implemented on every platform in this phase.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ProbeHostApi {
  /**
   * Returns the [MediaInfoMessage] for the media at [path].
   *
   * Declared here in full for the whole contract; only the Android implementation lands in
   * this plan. Failures throw `CompressVideoError` with the [path] never logged or included
   * in any diagnostic output outside the returned error detail.
   */
  suspend fun getMediaInfo(path: String): MediaInfoMessage

  companion object {
    /** The codec used by ProbeHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ProbeHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ProbeHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.compress_video.ProbeHostApi.getMediaInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getMediaInfo(pathArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Generates poster-frame thumbnails from a file. Declared here for contract completeness;
 * no platform implements this yet — that lands in a later plan in this phase.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ThumbnailHostApi {
  /**
   * Returns JPEG-encoded thumbnail bytes for the frame at [positionMs] in the media at
   * [path], encoded at [quality] (1-100), with the longer side capped at [maxDimensionPx]
   * when non-null (never upscaled).
   */
  suspend fun getThumbnail(path: String, positionMs: Long, quality: Long, maxDimensionPx: Long?): ByteArray
  /**
   * Same as [getThumbnail], but writes the JPEG to a file and returns its path. Writes to a
   * unique name in the app cache directory, or to [outputPath] when given.
   */
  suspend fun getThumbnailFile(path: String, positionMs: Long, quality: Long, maxDimensionPx: Long?, outputPath: String?): String

  companion object {
    /** The codec used by ThumbnailHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ThumbnailHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ThumbnailHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.compress_video.ThumbnailHostApi.getThumbnail$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val positionMsArg = args[1] as Long
            val qualityArg = args[2] as Long
            val maxDimensionPxArg = args[3] as Long?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getThumbnail(pathArg, positionMsArg, qualityArg, maxDimensionPxArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.compress_video.ThumbnailHostApi.getThumbnailFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val positionMsArg = args[1] as Long
            val qualityArg = args[2] as Long
            val maxDimensionPxArg = args[3] as Long?
            val outputPathArg = args[4] as String?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getThumbnailFile(pathArg, positionMsArg, qualityArg, maxDimensionPxArg, outputPathArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
