// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.danjjohnson.compress_video

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): CompressVideoError {
    return CompressVideoError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is CompressVideoError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class CompressVideoError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * How the audio track is handled during compression. Wire-level counterpart of the public
 * `AudioMode` enum in `lib/src/compress_options.dart`.
 */
enum class AudioModeMessage(val raw: Int) {
  /**
   * Keep the source audio track's encoding when it is already MP4-compatible AAC; re-encode
   * otherwise. This is the default.
   */
  PASSTHROUGH(0),
  /** Always re-encode the audio track to AAC, honouring the requested bitrate and channels. */
  REENCODE(1),
  /** Remove the audio track entirely. The result's `audioCodec` is `null`. */
  STRIP(2);

  companion object {
    fun ofRaw(raw: Int): AudioModeMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * The wire-format media info message returned by [ProbeHostApi.getMediaInfo].
 *
 * This is the generated, private counterpart of the public, hand-written `MediaInfo`
 * class in `lib/src/media_info.dart` — see that file for the documented public API.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MediaInfoMessage (
  /** Duration of the media, in milliseconds. */
  val durationMs: Long,
  /** Displayed (rotation-corrected) width, in pixels. Never the coded, pre-rotation width. */
  val widthPx: Long,
  /** Displayed (rotation-corrected) height, in pixels. Never the coded, pre-rotation height. */
  val heightPx: Long,
  /**
   * Unsigned clockwise rotation, in degrees, as reported by the platform before the
   * correction that produced [widthPx]/[heightPx] was applied. `0` for an unrotated clip.
   */
  val rotationDegrees: Long,
  /** Size of the underlying file, in bytes. */
  val sizeBytes: Long,
  /**
   * Normalised video codec token (`h264`, `hevc`, `av1`, `vp9`, `unknown`), or `null` when
   * the platform could not determine it. `null` is the sentinel for unknown — never an
   * empty string.
   */
  val videoCodec: String? = null,
  /**
   * Average video-track bitrate, in bits per second, or `null` when the platform could not
   * determine it. `null` is the sentinel for unknown — never `0`.
   */
  val videoBitrateBps: Long? = null,
  /**
   * Video frame rate, in frames per second, or `null` when the platform could not determine
   * it. `null` is the sentinel for unknown — never `0`. Never rounded to an integer.
   */
  val frameRateFps: Double? = null,
  /** Whether the media has at least one audio track. */
  val hasAudio: Boolean,
  /**
   * Whether the video is HDR (PQ or HLG transfer characteristic). `false` when the running
   * platform cannot determine HDR status — never an exception.
   */
  val isHdr: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaInfoMessage {
      val durationMs = pigeonVar_list[0] as Long
      val widthPx = pigeonVar_list[1] as Long
      val heightPx = pigeonVar_list[2] as Long
      val rotationDegrees = pigeonVar_list[3] as Long
      val sizeBytes = pigeonVar_list[4] as Long
      val videoCodec = pigeonVar_list[5] as String?
      val videoBitrateBps = pigeonVar_list[6] as Long?
      val frameRateFps = pigeonVar_list[7] as Double?
      val hasAudio = pigeonVar_list[8] as Boolean
      val isHdr = pigeonVar_list[9] as Boolean
      return MediaInfoMessage(durationMs, widthPx, heightPx, rotationDegrees, sizeBytes, videoCodec, videoBitrateBps, frameRateFps, hasAudio, isHdr)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      durationMs,
      widthPx,
      heightPx,
      rotationDegrees,
      sizeBytes,
      videoCodec,
      videoBitrateBps,
      frameRateFps,
      hasAudio,
      isHdr,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MediaInfoMessage
    return MessagesPigeonUtils.deepEquals(this.durationMs, other.durationMs) && MessagesPigeonUtils.deepEquals(this.widthPx, other.widthPx) && MessagesPigeonUtils.deepEquals(this.heightPx, other.heightPx) && MessagesPigeonUtils.deepEquals(this.rotationDegrees, other.rotationDegrees) && MessagesPigeonUtils.deepEquals(this.sizeBytes, other.sizeBytes) && MessagesPigeonUtils.deepEquals(this.videoCodec, other.videoCodec) && MessagesPigeonUtils.deepEquals(this.videoBitrateBps, other.videoBitrateBps) && MessagesPigeonUtils.deepEquals(this.frameRateFps, other.frameRateFps) && MessagesPigeonUtils.deepEquals(this.hasAudio, other.hasAudio) && MessagesPigeonUtils.deepEquals(this.isHdr, other.isHdr)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.widthPx)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.heightPx)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rotationDegrees)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sizeBytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.videoCodec)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.videoBitrateBps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.frameRateFps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hasAudio)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isHdr)
    return result
  }
  override fun toString(): String {
    return "MediaInfoMessage(durationMs=$durationMs, widthPx=$widthPx, heightPx=$heightPx, rotationDegrees=$rotationDegrees, sizeBytes=$sizeBytes, videoCodec=$videoCodec, videoBitrateBps=$videoBitrateBps, frameRateFps=$frameRateFps, hasAudio=$hasAudio, isHdr=$isHdr)"
  }
}

/**
 * A compression request, sent once per job via [CompressHostApi.startCompress] and also used
 * (identically) by [CompressHostApi.estimate] to predict what that request would produce.
 *
 * The preset named by the caller's `CompressOptions.preset` (see
 * `lib/src/compress_options.dart`) is resolved to a concrete [maxLongSidePx] plus
 * [videoBitrateBps] entirely on the Dart side before this message is built — no preset enum
 * crosses the channel, so a reader will not find one here.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CompressRequestMessage (
  /**
   * Explicit cap on the output's longer displayed side, in pixels, or `null` when the caller
   * did not set `CompressOptions.maxLongSidePx` -- in which case `SizeGuard` falls back to
   * [presetMaxLongSidePx]. Never the preset's own value pre-resolved into this field (that
   * was 02-02's tracer-only shape); this field is `null` unless the caller explicitly set it,
   * which is what lets the native side tell "explicit override" apart from "use the preset".
   */
  val maxLongSidePx: Long? = null,
  /**
   * Explicit target video bitrate, in bits per second, or `null` when the caller did not set
   * `CompressOptions.videoBitrateBps` -- in which case `SizeGuard` resolves it from
   * [targetSizeMb] if set, else scales [presetVideoBitrateBps] by the actual output
   * resolution and frame rate (SizeGuard.kt rule 6; this is the fix for the incumbent's
   * fixed-bitrate-regardless-of-resolution defect, PITFALLS.md row 13).
   */
  val videoBitrateBps: Long? = null,
  /** Target output file size, in megabytes, or `null` when no target size was requested. */
  val targetSizeMb: Double? = null,
  /**
   * The selected `CompressPreset`'s own nominal long-side cap, in pixels, always sent
   * regardless of any [maxLongSidePx] override -- the reference value SizeGuard's bitrate
   * scaling formula divides by. The preset enum itself never crosses the channel (02-02
   * decision, unchanged); only its two resolved numbers do.
   */
  val presetMaxLongSidePx: Long,
  /**
   * The selected `CompressPreset`'s own nominal video bitrate, in bits per second, always
   * sent regardless of any [videoBitrateBps] override -- the reference value SizeGuard scales
   * when neither an explicit bitrate nor a [targetSizeMb] was requested.
   */
  val presetVideoBitrateBps: Long,
  /**
   * Cap on the output's frame rate, in frames per second. Never upscales the input's own
   * frame rate — the effective cap is `min(maxFps, input fps)`.
   */
  val maxFps: Long,
  /** How the audio track is handled. See [AudioModeMessage]. */
  val audioMode: AudioModeMessage,
  /**
   * Target audio bitrate, in bits per second, when [audioMode] is
   * [AudioModeMessage.reencode]. `null` otherwise.
   */
  val audioBitrateBps: Long? = null,
  /**
   * Target audio channel count, when [audioMode] is [AudioModeMessage.reencode]. `null`
   * otherwise.
   */
  val audioChannels: Long? = null,
  /**
   * Start of the trim range, in milliseconds from the start of the input, or `null` for no
   * trim start.
   */
  val trimStartMs: Long? = null,
  /**
   * End of the trim range, in milliseconds from the start of the input, or `null` for no
   * trim end.
   */
  val trimEndMs: Long? = null,
  /**
   * Destination path for the compressed output, or `null` to use the plugin's own cache
   * directory with a name derived from the job id.
   */
  val outputPath: String? = null,
  /**
   * Requested output video codec. Only `"h264"` is accepted in this phase; HEVC opt-in is
   * Phase 4.
   */
  val videoCodec: String,
  /**
   * Requested HDR handling. Only `"toneMapToSdr"` is accepted in this phase; keep-HDR opt-in
   * is Phase 4.
   */
  val hdrMode: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CompressRequestMessage {
      val maxLongSidePx = pigeonVar_list[0] as Long?
      val videoBitrateBps = pigeonVar_list[1] as Long?
      val targetSizeMb = pigeonVar_list[2] as Double?
      val presetMaxLongSidePx = pigeonVar_list[3] as Long
      val presetVideoBitrateBps = pigeonVar_list[4] as Long
      val maxFps = pigeonVar_list[5] as Long
      val audioMode = pigeonVar_list[6] as AudioModeMessage
      val audioBitrateBps = pigeonVar_list[7] as Long?
      val audioChannels = pigeonVar_list[8] as Long?
      val trimStartMs = pigeonVar_list[9] as Long?
      val trimEndMs = pigeonVar_list[10] as Long?
      val outputPath = pigeonVar_list[11] as String?
      val videoCodec = pigeonVar_list[12] as String
      val hdrMode = pigeonVar_list[13] as String
      return CompressRequestMessage(maxLongSidePx, videoBitrateBps, targetSizeMb, presetMaxLongSidePx, presetVideoBitrateBps, maxFps, audioMode, audioBitrateBps, audioChannels, trimStartMs, trimEndMs, outputPath, videoCodec, hdrMode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      maxLongSidePx,
      videoBitrateBps,
      targetSizeMb,
      presetMaxLongSidePx,
      presetVideoBitrateBps,
      maxFps,
      audioMode,
      audioBitrateBps,
      audioChannels,
      trimStartMs,
      trimEndMs,
      outputPath,
      videoCodec,
      hdrMode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CompressRequestMessage
    return MessagesPigeonUtils.deepEquals(this.maxLongSidePx, other.maxLongSidePx) && MessagesPigeonUtils.deepEquals(this.videoBitrateBps, other.videoBitrateBps) && MessagesPigeonUtils.deepEquals(this.targetSizeMb, other.targetSizeMb) && MessagesPigeonUtils.deepEquals(this.presetMaxLongSidePx, other.presetMaxLongSidePx) && MessagesPigeonUtils.deepEquals(this.presetVideoBitrateBps, other.presetVideoBitrateBps) && MessagesPigeonUtils.deepEquals(this.maxFps, other.maxFps) && MessagesPigeonUtils.deepEquals(this.audioMode, other.audioMode) && MessagesPigeonUtils.deepEquals(this.audioBitrateBps, other.audioBitrateBps) && MessagesPigeonUtils.deepEquals(this.audioChannels, other.audioChannels) && MessagesPigeonUtils.deepEquals(this.trimStartMs, other.trimStartMs) && MessagesPigeonUtils.deepEquals(this.trimEndMs, other.trimEndMs) && MessagesPigeonUtils.deepEquals(this.outputPath, other.outputPath) && MessagesPigeonUtils.deepEquals(this.videoCodec, other.videoCodec) && MessagesPigeonUtils.deepEquals(this.hdrMode, other.hdrMode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxLongSidePx)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.videoBitrateBps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.targetSizeMb)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.presetMaxLongSidePx)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.presetVideoBitrateBps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxFps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.audioMode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.audioBitrateBps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.audioChannels)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.trimStartMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.trimEndMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.outputPath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.videoCodec)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hdrMode)
    return result
  }
  override fun toString(): String {
    return "CompressRequestMessage(maxLongSidePx=$maxLongSidePx, videoBitrateBps=$videoBitrateBps, targetSizeMb=$targetSizeMb, presetMaxLongSidePx=$presetMaxLongSidePx, presetVideoBitrateBps=$presetVideoBitrateBps, maxFps=$maxFps, audioMode=$audioMode, audioBitrateBps=$audioBitrateBps, audioChannels=$audioChannels, trimStartMs=$trimStartMs, trimEndMs=$trimEndMs, outputPath=$outputPath, videoCodec=$videoCodec, hdrMode=$hdrMode)"
  }
}

/**
 * The typed result of a completed compression job. Every field is populated from a re-probe
 * of the finished output file, never from the export engine's own approximate fields — see
 * 02-RESEARCH.md Pitfall 4.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CompressResultMessage (
  /** Absolute path to the compressed output file. */
  val outputPath: String,
  /** Size of the input file, in bytes. */
  val inputBytes: Long,
  /** Size of the output file, in bytes. */
  val outputBytes: Long,
  /** Displayed (rotation-corrected) width of the output, in pixels. */
  val widthPx: Long,
  /** Displayed (rotation-corrected) height of the output, in pixels. */
  val heightPx: Long,
  /** Duration of the output, in milliseconds, from a re-probe of the finished file. */
  val durationMs: Long,
  /** Normalised video codec of the output (for example `h264`). */
  val videoCodec: String,
  /**
   * Normalised audio codec of the output, or `null` when the audio track was stripped or the
   * source had none.
   */
  val audioCodec: String? = null,
  /**
   * Whether the job ran as a transmux (container remux with no video re-encode) rather than
   * a full encode.
   */
  val transmuxed: Boolean,
  /**
   * Whether the original input bytes were copied to [outputPath] because compressing would
   * have produced an equal-or-larger file. `outputPath` always names a file the plugin owns
   * (never the caller's original input path) when this is `true`.
   */
  val usedOriginal: Boolean,
  /** Reserved for Phase 4's HDR tone-mapping. Always `false` in this phase. */
  val toneMapped: Boolean,
  /** Reserved for Phase 4's HEVC hardware-fallback handling. Always `false` in this phase. */
  val hevcFallback: Boolean,
  /** Whether the audio track was re-encoded (as opposed to passed through or stripped). */
  val audioReencoded: Boolean,
  /** Wall-clock time the compression took, in milliseconds. */
  val elapsedMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CompressResultMessage {
      val outputPath = pigeonVar_list[0] as String
      val inputBytes = pigeonVar_list[1] as Long
      val outputBytes = pigeonVar_list[2] as Long
      val widthPx = pigeonVar_list[3] as Long
      val heightPx = pigeonVar_list[4] as Long
      val durationMs = pigeonVar_list[5] as Long
      val videoCodec = pigeonVar_list[6] as String
      val audioCodec = pigeonVar_list[7] as String?
      val transmuxed = pigeonVar_list[8] as Boolean
      val usedOriginal = pigeonVar_list[9] as Boolean
      val toneMapped = pigeonVar_list[10] as Boolean
      val hevcFallback = pigeonVar_list[11] as Boolean
      val audioReencoded = pigeonVar_list[12] as Boolean
      val elapsedMs = pigeonVar_list[13] as Long
      return CompressResultMessage(outputPath, inputBytes, outputBytes, widthPx, heightPx, durationMs, videoCodec, audioCodec, transmuxed, usedOriginal, toneMapped, hevcFallback, audioReencoded, elapsedMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      outputPath,
      inputBytes,
      outputBytes,
      widthPx,
      heightPx,
      durationMs,
      videoCodec,
      audioCodec,
      transmuxed,
      usedOriginal,
      toneMapped,
      hevcFallback,
      audioReencoded,
      elapsedMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CompressResultMessage
    return MessagesPigeonUtils.deepEquals(this.outputPath, other.outputPath) && MessagesPigeonUtils.deepEquals(this.inputBytes, other.inputBytes) && MessagesPigeonUtils.deepEquals(this.outputBytes, other.outputBytes) && MessagesPigeonUtils.deepEquals(this.widthPx, other.widthPx) && MessagesPigeonUtils.deepEquals(this.heightPx, other.heightPx) && MessagesPigeonUtils.deepEquals(this.durationMs, other.durationMs) && MessagesPigeonUtils.deepEquals(this.videoCodec, other.videoCodec) && MessagesPigeonUtils.deepEquals(this.audioCodec, other.audioCodec) && MessagesPigeonUtils.deepEquals(this.transmuxed, other.transmuxed) && MessagesPigeonUtils.deepEquals(this.usedOriginal, other.usedOriginal) && MessagesPigeonUtils.deepEquals(this.toneMapped, other.toneMapped) && MessagesPigeonUtils.deepEquals(this.hevcFallback, other.hevcFallback) && MessagesPigeonUtils.deepEquals(this.audioReencoded, other.audioReencoded) && MessagesPigeonUtils.deepEquals(this.elapsedMs, other.elapsedMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.outputPath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.inputBytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.outputBytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.widthPx)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.heightPx)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.videoCodec)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.audioCodec)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.transmuxed)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.usedOriginal)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.toneMapped)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hevcFallback)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.audioReencoded)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.elapsedMs)
    return result
  }
  override fun toString(): String {
    return "CompressResultMessage(outputPath=$outputPath, inputBytes=$inputBytes, outputBytes=$outputBytes, widthPx=$widthPx, heightPx=$heightPx, durationMs=$durationMs, videoCodec=$videoCodec, audioCodec=$audioCodec, transmuxed=$transmuxed, usedOriginal=$usedOriginal, toneMapped=$toneMapped, hevcFallback=$hevcFallback, audioReencoded=$audioReencoded, elapsedMs=$elapsedMs)"
  }
}

/**
 * The typed, pre-flight prediction of what a [CompressRequestMessage] would produce, without
 * running an actual encode.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class EstimateMessage (
  /** Predicted size of the output, in bytes. */
  val outputBytes: Long,
  /** Predicted duration of the output, in milliseconds. */
  val durationMs: Long,
  /** Predicted displayed width of the output, in pixels. */
  val widthPx: Long,
  /** Predicted displayed height of the output, in pixels. */
  val heightPx: Long,
  /** Whether the request would run as a transmux rather than a full encode. */
  val wouldTransmux: Boolean,
  /** Whether the request would fall back to copying the original input rather than encoding. */
  val wouldUseOriginal: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EstimateMessage {
      val outputBytes = pigeonVar_list[0] as Long
      val durationMs = pigeonVar_list[1] as Long
      val widthPx = pigeonVar_list[2] as Long
      val heightPx = pigeonVar_list[3] as Long
      val wouldTransmux = pigeonVar_list[4] as Boolean
      val wouldUseOriginal = pigeonVar_list[5] as Boolean
      return EstimateMessage(outputBytes, durationMs, widthPx, heightPx, wouldTransmux, wouldUseOriginal)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      outputBytes,
      durationMs,
      widthPx,
      heightPx,
      wouldTransmux,
      wouldUseOriginal,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EstimateMessage
    return MessagesPigeonUtils.deepEquals(this.outputBytes, other.outputBytes) && MessagesPigeonUtils.deepEquals(this.durationMs, other.durationMs) && MessagesPigeonUtils.deepEquals(this.widthPx, other.widthPx) && MessagesPigeonUtils.deepEquals(this.heightPx, other.heightPx) && MessagesPigeonUtils.deepEquals(this.wouldTransmux, other.wouldTransmux) && MessagesPigeonUtils.deepEquals(this.wouldUseOriginal, other.wouldUseOriginal)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.outputBytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.widthPx)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.heightPx)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.wouldTransmux)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.wouldUseOriginal)
    return result
  }
  override fun toString(): String {
    return "EstimateMessage(outputBytes=$outputBytes, durationMs=$durationMs, widthPx=$widthPx, heightPx=$heightPx, wouldTransmux=$wouldTransmux, wouldUseOriginal=$wouldUseOriginal)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AudioModeMessage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaInfoMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CompressRequestMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CompressResultMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EstimateMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AudioModeMessage -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is MediaInfoMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is CompressRequestMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is CompressResultMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is EstimateMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Reads media info from a file. Implemented on every platform in this phase.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ProbeHostApi {
  /**
   * Returns the [MediaInfoMessage] for the media at [path].
   *
   * Declared here in full for the whole contract; only the Android implementation lands in
   * this plan. Failures throw `CompressVideoError` with the [path] never logged or included
   * in any diagnostic output outside the returned error detail.
   */
  suspend fun getMediaInfo(path: String): MediaInfoMessage

  companion object {
    /** The codec used by ProbeHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ProbeHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ProbeHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.compress_video.ProbeHostApi.getMediaInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getMediaInfo(pathArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Generates poster-frame thumbnails from a file. Declared here for contract completeness;
 * no platform implements this yet — that lands in a later plan in this phase.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ThumbnailHostApi {
  /**
   * Returns JPEG-encoded thumbnail bytes for the frame at [positionMs] in the media at
   * [path], encoded at [quality] (1-100), with the longer side capped at [maxDimensionPx]
   * when non-null (never upscaled).
   */
  suspend fun getThumbnail(path: String, positionMs: Long, quality: Long, maxDimensionPx: Long?): ByteArray
  /**
   * Same as [getThumbnail], but writes the JPEG to a file and returns its path. Writes to a
   * unique name in the app cache directory, or to [outputPath] when given.
   */
  suspend fun getThumbnailFile(path: String, positionMs: Long, quality: Long, maxDimensionPx: Long?, outputPath: String?): String

  companion object {
    /** The codec used by ThumbnailHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ThumbnailHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ThumbnailHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.compress_video.ThumbnailHostApi.getThumbnail$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val positionMsArg = args[1] as Long
            val qualityArg = args[2] as Long
            val maxDimensionPxArg = args[3] as Long?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getThumbnail(pathArg, positionMsArg, qualityArg, maxDimensionPxArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.compress_video.ThumbnailHostApi.getThumbnailFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val positionMsArg = args[1] as Long
            val qualityArg = args[2] as Long
            val maxDimensionPxArg = args[3] as Long?
            val outputPathArg = args[4] as String?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getThumbnailFile(pathArg, positionMsArg, qualityArg, maxDimensionPxArg, outputPathArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Runs and manages compression jobs. Implemented per-platform; this phase implements Android
 * only.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface CompressHostApi {
  /**
   * Starts a compression job for the media at [path], identified by the caller-generated
   * [jobId], with the given [request]. [jobId] is generated by the caller (Dart) so two jobs
   * started back to back never race on native-side id generation.
   */
  suspend fun startCompress(path: String, jobId: String, request: CompressRequestMessage): CompressResultMessage
  /** Cancels the job identified by [jobId]. A no-op if the job has already finished. */
  suspend fun cancel(jobId: String)
  /**
   * Returns a pre-flight [EstimateMessage] for compressing the media at [path] with
   * [request], without running an actual encode.
   */
  suspend fun estimate(path: String, request: CompressRequestMessage): EstimateMessage
  /** Deletes every file the plugin has written to its own cache directory. */
  suspend fun clearCache()

  companion object {
    /** The codec used by CompressHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `CompressHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CompressHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.compress_video.CompressHostApi.startCompress$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val jobIdArg = args[1] as String
            val requestArg = args[2] as CompressRequestMessage
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.startCompress(pathArg, jobIdArg, requestArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.compress_video.CompressHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val jobIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.cancel(jobIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.compress_video.CompressHostApi.estimate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val requestArg = args[1] as CompressRequestMessage
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.estimate(pathArg, requestArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.compress_video.CompressHostApi.clearCache$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.clearCache()
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Progress notifications from native code back to Dart, keyed by job id. Fire-and-forget:
 * Dart does not reply to this call.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class CompressVideoFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CompressVideoFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  /** Reports that the job identified by [jobId] has reached [percent] (0 to 100) complete. */
  suspend fun onProgress(jobIdArg: String, percentArg: Double)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.compress_video.CompressVideoFlutterApi.onProgress$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(jobIdArg, percentArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(CompressVideoError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
