#!/usr/bin/env bash
# Generate the corpus: eleven structurally phone-like (or deliberately damaged/synthetic-HDR)
# clips.
#
#   portrait_rot90.mp4          - 1920x1080 coded, 90-degree clockwise tkhd
#                                  display matrix (as an iPhone writes portrait
#                                  video), H.264 + AAC stereo, ~4s, burnt-in ms
#                                  timecode plus an 8-bucket colour-patch
#                                  schedule for the thumbnail probe test.
#   small_480p.mp4               - already-small, low-bitrate clip, H.264 +
#                                  AAC, no rotation matrix.
#   noaudio_720p.mp4             - no audio stream at all, no rotation matrix.
#   portrait_hibitrate_1080p60.mp4 - 1920x1080 coded, 60fps, high-entropy
#                                  (mandelbrot) source at ~8Mbps so a preset
#                                  encode can only shrink it by genuinely
#                                  re-encoding; same colour-patch schedule and
#                                  90-degree tkhd matrix as portrait_rot90.mp4,
#                                  plus a 24px pure-white border for the
#                                  no-letterbox edge probe (Phase 2).
#   truncated_mdat.mp4           - a faststart MP4 truncated mid-mdat: the
#                                  moov atom (and therefore duration) survives,
#                                  but decoding the media data fails on a real
#                                  platform codec (Phase 2).
#   trim_source_10s.mp4          - 1280x720 coded, 30fps, H.264 + AAC stereo,
#                                  no rotation matrix, ~1Mbps, 10s, burnt-in ms
#                                  timecode, explicit 30-frame GOP. Exists
#                                  because no other clip is long enough to
#                                  express a 2000->7000ms trim (Phase 3, D-13).
#   hdr_hlg10.mp4                 - 1280x720, 2s, HEVC Main10, HLG (arib-std-b67)
#                                  transfer, BT.2020 primaries, no audio, four
#                                  160x160 red/green/blue/white colour patches
#                                  (Phase 4, D-01).
#   hdr_pq10.mp4                  - Same geometry/patches as hdr_hlg10.mp4, but
#                                  PQ/SMPTE-2084 transfer with mastering-display
#                                  and max-CLL side data (Phase 4, D-01).
#   pcm_audio_480p.mov            - 854x480, H.264 + LPCM stereo audio in a .mov
#                                  container (not .mp4 -- ffmpeg's ISO-MP4 PCM
#                                  fourcc isn't recognized by Android's
#                                  MediaExtractor; confirmed live, Phase 4, D-10).
#   surround51_480p.mp4           - 854x480, H.264 + 6-channel (5.1) AAC audio
#                                  at 384kbps (Phase 4, D-09).
#   uhd_4k60.mp4                  - 3840x2160 at 60fps, 2s, no audio, high-entropy
#                                  (mandelbrot) H.264 capped to a few MB (Phase 4,
#                                  D-12).
#
# Reserved slot: hdr_dolbyvision_p8.mp4 (Dolby Vision profile 8) is NOT generated by this
# script -- ffmpeg cannot author Dolby Vision RPU metadata. It is a real-phone-clip-only fixture;
# see corpus/README.md "Reserved slots" and QUESTIONS.md #4.
#
# `ffmpeg -metadata:s:v:0 rotate=90` is a verified no-op on the installed
# ffmpeg 6.1.1-3ubuntu5 (see 01-RESEARCH.md Common Pitfalls #1/#2), so the
# portrait clips' display matrices are written directly via patch_rotation.py
# after encoding.
#
# Every assertion below runs unconditionally (no `|| true`, no
# `2>/dev/null` around the assertion itself) and exits non-zero naming the
# clip on failure - a script that "succeeds" here must mean every structural
# property actually holds.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

FONT=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
DEFAULT_MAX_BYTES=1500000

if [ ! -f "$FONT" ]; then
  echo "ERROR: font not found at $FONT (required for the portrait clip's burnt-in timecode)" >&2
  exit 1
fi

fail() {
  local clip="$1" msg="$2"
  echo "ASSERTION FAILED for $clip: $msg" >&2
  exit 1
}

# $2 (max_bytes) is per-clip so a high-bitrate fixture can carry a wider cap
# without raising it for any other clip; it defaults to DEFAULT_MAX_BYTES so
# every pre-existing call site keeps its original 1.5MB cap unchanged.
assert_size() {
  local clip="$1"
  local max_bytes="${2:-$DEFAULT_MAX_BYTES}"
  local size
  size=$(stat -c%s "$clip")
  if [ "$size" -gt "$max_bytes" ]; then
    fail "$clip" "size ${size} bytes exceeds ${max_bytes} byte cap"
  fi
}

probe_json() {
  ffprobe -v quiet -print_format json -show_streams -show_format "$1"
}

# ---------------------------------------------------------------------------
# Clip A: portrait_rot90.mp4
# ---------------------------------------------------------------------------
echo "Generating portrait_rot90.mp4..."

PORTRAIT=portrait_rot90.mp4
PORTRAIT_TMP=portrait_rot90.tmp.mp4

# Eight 500ms colour buckets (K=0..7) covering the 4s duration, painted in
# order so a later bucket overwrites an earlier one at any shared boundary.
# Colours chosen to stay far apart in every RGB channel after JPEG loss.
DRAWBOXES=""
COLORS=(red green blue yellow magenta cyan white black)
for k in "${!COLORS[@]}"; do
  start=$(awk -v k="$k" 'BEGIN{printf "%.1f", k*0.5}')
  end=$(awk -v k="$k" 'BEGIN{printf "%.1f", (k+1)*0.5}')
  DRAWBOXES="${DRAWBOXES},drawbox=x=1600:y=60:w=200:h=200:color=${COLORS[$k]}:t=fill:enable='between(t,${start},${end})'"
done

ffmpeg -y -loglevel error \
  -f lavfi -i "testsrc=size=1920x1080:rate=30:duration=4" \
  -f lavfi -i "sine=frequency=440:sample_rate=48000:duration=4" \
  -filter_complex "[0:v]drawtext=fontfile=${FONT}:text='%{eif\:t*1000\:d}ms':fontcolor=white:fontsize=48:x=10:y=10:box=1:boxcolor=black${DRAWBOXES}[v]" \
  -map "[v]" -map 1:a \
  -c:v libx264 -pix_fmt yuv420p -preset veryfast -crf 30 -g 30 \
  -threads 1 -x264-params threads=1:sliced_threads=0 \
  -c:a aac -b:a 96k -ac 2 -ar 48000 \
  -movflags +faststart \
  -shortest \
  "$PORTRAIT_TMP"

mv "$PORTRAIT_TMP" "$PORTRAIT"
python3 patch_rotation.py "$PORTRAIT" 1080 90

PORTRAIT_JSON=$(probe_json "$PORTRAIT")
ROTATION=$(echo "$PORTRAIT_JSON" | jq -r '[.streams[] | select(.codec_type=="video") | .side_data_list[]? | select(.side_data_type=="Display Matrix") | .rotation] | first // empty')
if [ "$ROTATION" != "-90" ]; then
  fail "$PORTRAIT" "expected Display Matrix rotation -90, got '${ROTATION}'"
fi
CODED_W=$(echo "$PORTRAIT_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .width')
CODED_H=$(echo "$PORTRAIT_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .height')
if [ "$CODED_W" != "1920" ] || [ "$CODED_H" != "1080" ]; then
  fail "$PORTRAIT" "expected coded dimensions 1920x1080, got ${CODED_W}x${CODED_H}"
fi
assert_size "$PORTRAIT" "$DEFAULT_MAX_BYTES"
echo "OK: $PORTRAIT (Display Matrix rotation -90, coded ${CODED_W}x${CODED_H}, $(stat -c%s "$PORTRAIT") bytes)"

# ---------------------------------------------------------------------------
# Clip B: small_480p.mp4
# ---------------------------------------------------------------------------
echo "Generating small_480p.mp4..."

SMALL=small_480p.mp4
SMALL_TMP=small_480p.tmp.mp4

ffmpeg -y -loglevel error \
  -f lavfi -i "testsrc=size=854x480:rate=30:duration=3" \
  -f lavfi -i "sine=frequency=440:sample_rate=48000:duration=3" \
  -map 0:v -map 1:a \
  -c:v libx264 -pix_fmt yuv420p -preset veryfast -b:v 300k -maxrate 350k -bufsize 600k \
  -threads 1 -x264-params threads=1:sliced_threads=0 \
  -c:a aac -b:a 64k -ac 2 \
  -shortest \
  "$SMALL_TMP"

mv "$SMALL_TMP" "$SMALL"

SMALL_JSON=$(probe_json "$SMALL")
V_COUNT=$(echo "$SMALL_JSON" | jq '[.streams[] | select(.codec_type=="video")] | length')
A_COUNT=$(echo "$SMALL_JSON" | jq '[.streams[] | select(.codec_type=="audio")] | length')
if [ "$V_COUNT" != "1" ] || [ "$A_COUNT" != "1" ]; then
  fail "$SMALL" "expected exactly 1 video + 1 audio stream, got ${V_COUNT} video + ${A_COUNT} audio"
fi
SIDE_DATA=$(echo "$SMALL_JSON" | jq '[.streams[] | select(.codec_type=="video") | .side_data_list[]?] | length')
if [ "$SIDE_DATA" != "0" ]; then
  fail "$SMALL" "expected no side data (no display matrix), found ${SIDE_DATA} entries"
fi
AUDIO_CODEC=$(echo "$SMALL_JSON" | jq -r '.streams[] | select(.codec_type=="audio") | .codec_name')
if [ "$AUDIO_CODEC" != "aac" ]; then
  fail "$SMALL" "expected aac audio codec, got ${AUDIO_CODEC}"
fi
assert_size "$SMALL" "$DEFAULT_MAX_BYTES"
echo "OK: $SMALL (1 video + 1 audio, no side data, $(stat -c%s "$SMALL") bytes)"

# ---------------------------------------------------------------------------
# Clip C: noaudio_720p.mp4
# ---------------------------------------------------------------------------
echo "Generating noaudio_720p.mp4..."

NOAUDIO=noaudio_720p.mp4
NOAUDIO_TMP=noaudio_720p.tmp.mp4

ffmpeg -y -loglevel error \
  -f lavfi -i "testsrc=size=1280x720:rate=30:duration=3" \
  -an \
  -c:v libx264 -pix_fmt yuv420p -preset veryfast -crf 30 \
  -threads 1 -x264-params threads=1:sliced_threads=0 \
  "$NOAUDIO_TMP"

mv "$NOAUDIO_TMP" "$NOAUDIO"

NOAUDIO_JSON=$(probe_json "$NOAUDIO")
NA_A_COUNT=$(echo "$NOAUDIO_JSON" | jq '[.streams[] | select(.codec_type=="audio")] | length')
if [ "$NA_A_COUNT" != "0" ]; then
  fail "$NOAUDIO" "expected zero audio streams, found ${NA_A_COUNT}"
fi
assert_size "$NOAUDIO" "$DEFAULT_MAX_BYTES"
echo "OK: $NOAUDIO (0 audio streams, $(stat -c%s "$NOAUDIO") bytes)"

# ---------------------------------------------------------------------------
# Clip D: portrait_hibitrate_1080p60.mp4
# ---------------------------------------------------------------------------
# Every existing corpus clip is far below every preset bitrate Phase 2
# defines (portrait_rot90.mp4 is ~193kbps; p360, the lowest preset, starts at
# 800kbps) - a "preset shrinks the file" test against them can only ever hit
# the never-larger path. This clip uses a high-entropy (mandelbrot) source at
# 60fps and ~8Mbps so genuine re-encoding, the 30fps frame-rate cap, upright
# portrait output and the no-letterbox check are all observable in one
# fixture. Same 8-bucket colour-patch schedule and coded coordinates as
# portrait_rot90.mp4 (the existing thumbnail probe contract applies
# unchanged), plus a 24px pure-white border for the no-letterbox edge probe.
echo "Generating portrait_hibitrate_1080p60.mp4..."

HIBITRATE=portrait_hibitrate_1080p60.mp4
HIBITRATE_TMP=portrait_hibitrate_1080p60.tmp.mp4
HIBITRATE_MAX_BYTES=6000000
HIBITRATE_MIN_BYTES=2000000
BORDER_PX=24

# Same colour-patch geometry/order/timing as portrait_rot90.mp4's DRAWBOXES.
HIBITRATE_DRAWBOXES=""
for k in "${!COLORS[@]}"; do
  start=$(awk -v k="$k" 'BEGIN{printf "%.1f", k*0.5}')
  end=$(awk -v k="$k" 'BEGIN{printf "%.1f", (k+1)*0.5}')
  HIBITRATE_DRAWBOXES="${HIBITRATE_DRAWBOXES},drawbox=x=1600:y=60:w=200:h=200:color=${COLORS[$k]}:t=fill:enable='between(t,${start},${end})'"
done

# A solid pure-white 24px border around the whole coded frame, drawn AFTER
# the colour patch so nothing overwrites it. verify_corpus.sh's edgeProbe
# samples inset points on this border; a letterboxed (black-bar) output
# would fail that sample.
HIBITRATE_BORDER=",drawbox=x=0:y=0:w=1920:h=${BORDER_PX}:color=white:t=fill"
HIBITRATE_BORDER="${HIBITRATE_BORDER},drawbox=x=0:y=$((1080 - BORDER_PX)):w=1920:h=${BORDER_PX}:color=white:t=fill"
HIBITRATE_BORDER="${HIBITRATE_BORDER},drawbox=x=0:y=0:w=${BORDER_PX}:h=1080:color=white:t=fill"
HIBITRATE_BORDER="${HIBITRATE_BORDER},drawbox=x=$((1920 - BORDER_PX)):y=0:w=${BORDER_PX}:h=1080:color=white:t=fill"

ffmpeg -y -loglevel error \
  -f lavfi -i "mandelbrot=size=1920x1080:rate=60" \
  -f lavfi -i "sine=frequency=440:sample_rate=48000:duration=4" \
  -filter_complex "[0:v]drawtext=fontfile=${FONT}:text='%{eif\:t*1000\:d}ms':fontcolor=white:fontsize=48:x=10:y=10:box=1:boxcolor=black${HIBITRATE_DRAWBOXES}${HIBITRATE_BORDER}[v]" \
  -map "[v]" -map 1:a \
  -c:v libx264 -pix_fmt yuv420p -preset veryfast -g 60 -b:v 8M -maxrate 8M -bufsize 8M \
  -threads 1 -x264-params threads=1:sliced_threads=0 \
  -c:a aac -b:a 128k -ac 2 -ar 48000 \
  -movflags +faststart \
  -shortest \
  "$HIBITRATE_TMP"

mv "$HIBITRATE_TMP" "$HIBITRATE"
python3 patch_rotation.py "$HIBITRATE" 1080 90

HIBITRATE_JSON=$(probe_json "$HIBITRATE")
HIBITRATE_ROTATION=$(echo "$HIBITRATE_JSON" | jq -r '[.streams[] | select(.codec_type=="video") | .side_data_list[]? | select(.side_data_type=="Display Matrix") | .rotation] | first // empty')
if [ "$HIBITRATE_ROTATION" != "-90" ]; then
  fail "$HIBITRATE" "expected Display Matrix rotation -90, got '${HIBITRATE_ROTATION}'"
fi
HIBITRATE_CODED_W=$(echo "$HIBITRATE_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .width')
HIBITRATE_CODED_H=$(echo "$HIBITRATE_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .height')
if [ "$HIBITRATE_CODED_W" != "1920" ] || [ "$HIBITRATE_CODED_H" != "1080" ]; then
  fail "$HIBITRATE" "expected coded dimensions 1920x1080, got ${HIBITRATE_CODED_W}x${HIBITRATE_CODED_H}"
fi
HIBITRATE_FPS_RAW=$(echo "$HIBITRATE_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .avg_frame_rate')
HIBITRATE_FPS=$(awk -F/ -v r="$HIBITRATE_FPS_RAW" 'BEGIN{split(r,a,"/"); if (a[2]+0==0) print "0"; else printf "%.0f", a[1]/a[2]}')
if [ "$HIBITRATE_FPS" != "60" ]; then
  fail "$HIBITRATE" "expected avg frame rate 60, got ${HIBITRATE_FPS_RAW} (~${HIBITRATE_FPS})"
fi
HIBITRATE_BITRATE=$(echo "$HIBITRATE_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .bit_rate // 0')
if [ "$HIBITRATE_BITRATE" -le 6000000 ]; then
  fail "$HIBITRATE" "expected video bitrate above 6000000, got ${HIBITRATE_BITRATE}"
fi
HIBITRATE_V_COUNT=$(echo "$HIBITRATE_JSON" | jq '[.streams[] | select(.codec_type=="video")] | length')
HIBITRATE_A_COUNT=$(echo "$HIBITRATE_JSON" | jq '[.streams[] | select(.codec_type=="audio")] | length')
if [ "$HIBITRATE_V_COUNT" != "1" ] || [ "$HIBITRATE_A_COUNT" != "1" ]; then
  fail "$HIBITRATE" "expected exactly 1 video + 1 audio stream, got ${HIBITRATE_V_COUNT} video + ${HIBITRATE_A_COUNT} audio"
fi
assert_size "$HIBITRATE" "$HIBITRATE_MAX_BYTES"
HIBITRATE_SIZE=$(stat -c%s "$HIBITRATE")
if [ "$HIBITRATE_SIZE" -le "$HIBITRATE_MIN_BYTES" ]; then
  fail "$HIBITRATE" "size ${HIBITRATE_SIZE} bytes is not above ${HIBITRATE_MIN_BYTES} byte floor"
fi
echo "OK: $HIBITRATE (Display Matrix rotation -90, coded ${HIBITRATE_CODED_W}x${HIBITRATE_CODED_H}, ${HIBITRATE_FPS}fps, bitrate ${HIBITRATE_BITRATE}, ${HIBITRATE_SIZE} bytes)"

# ---------------------------------------------------------------------------
# Clip E: truncated_mdat.mp4
# ---------------------------------------------------------------------------
# Deliberately structurally damaged: faststart writes the moov atom at the
# front of the file, so ffprobe (and path validation) still see a valid
# video stream and duration after truncation, but the media data itself is
# incomplete - a decode of this file reaches the platform codec and fails
# there, giving the error-mapping work a real ExportException to observe
# instead of an assumption from a javadoc. Has no sidecar on purpose (see
# verify_corpus.sh) - it is never fed to a "does the output match ground
# truth" assertion, only to "does decoding it fail the way we expect".
echo "Generating truncated_mdat.mp4..."

TRUNCATED=truncated_mdat.mp4
TRUNCATED_SRC=truncated_mdat.src.mp4

ffmpeg -y -loglevel error \
  -f lavfi -i "testsrc=size=854x480:rate=30:duration=2" \
  -f lavfi -i "sine=frequency=440:sample_rate=48000:duration=2" \
  -map 0:v -map 1:a \
  -c:v libx264 -pix_fmt yuv420p -preset veryfast -crf 30 \
  -threads 1 -x264-params threads=1:sliced_threads=0 \
  -c:a aac -b:a 64k -ac 2 \
  -movflags +faststart \
  -shortest \
  "$TRUNCATED_SRC"

SRC_SIZE=$(stat -c%s "$TRUNCATED_SRC")
TRUNCATED_SIZE=$(awk -v s="$SRC_SIZE" 'BEGIN{printf "%d", s*0.6}')
head -c "$TRUNCATED_SIZE" "$TRUNCATED_SRC" > "$TRUNCATED"
rm -f "$TRUNCATED_SRC"

TRUNCATED_DURATION=$(ffprobe -v quiet -show_entries format=duration -of csv=p=0 "$TRUNCATED" 2>/dev/null || true)
if [ -z "$TRUNCATED_DURATION" ]; then
  fail "$TRUNCATED" "expected ffprobe to still report a duration after truncation, got empty"
fi
TRUNCATED_HAS_VIDEO=$(ffprobe -v quiet -select_streams v:0 -show_entries stream=codec_type -of csv=p=0 "$TRUNCATED" 2>/dev/null || true)
if [ "$TRUNCATED_HAS_VIDEO" != "video" ]; then
  fail "$TRUNCATED" "expected ffprobe to still report a video stream after truncation, got '${TRUNCATED_HAS_VIDEO}'"
fi
echo "OK: $TRUNCATED (truncated to 60% of ${SRC_SIZE} bytes = $(stat -c%s "$TRUNCATED") bytes, duration ${TRUNCATED_DURATION}s still readable)"

# ---------------------------------------------------------------------------
# Clip F: trim_source_10s.mp4
# ---------------------------------------------------------------------------
# Every other clip in this corpus is 3-4s; the phase 3 trim criterion
# (2000ms -> 7000ms) is unsatisfiable against any of them. This clip is 10s,
# 1280x720 coded, 30fps, H.264 + AAC stereo at 128kbps/48kHz, ~1Mbps, no
# rotation matrix, with the same burnt-in millisecond timecode style as the
# portrait clips (so a trimmed output's first frame is checkable by eye and
# by pixel probe) and an explicit 30-frame GOP (-g 30) so the keyframe
# structure a trim reader has to seek within is a stated property of the
# fixture, not an ffmpeg default that could silently change later.
echo "Generating trim_source_10s.mp4..."

TRIM=trim_source_10s.mp4
TRIM_TMP=trim_source_10s.tmp.mp4
TRIM_MAX_BYTES=2000000
TRIM_GOP=30

ffmpeg -y -loglevel error \
  -f lavfi -i "testsrc=size=1280x720:rate=30:duration=10" \
  -f lavfi -i "sine=frequency=440:sample_rate=48000:duration=10" \
  -filter_complex "[0:v]drawtext=fontfile=${FONT}:text='%{eif\:t*1000\:d}ms':fontcolor=white:fontsize=48:x=10:y=10:box=1:boxcolor=black[v]" \
  -map "[v]" -map 1:a \
  -c:v libx264 -pix_fmt yuv420p -preset veryfast -b:v 1M -maxrate 1M -bufsize 2M -g "$TRIM_GOP" \
  -threads 1 -x264-params threads=1:sliced_threads=0 \
  -c:a aac -b:a 128k -ac 2 -ar 48000 \
  -movflags +faststart \
  -shortest \
  "$TRIM_TMP"

mv "$TRIM_TMP" "$TRIM"

TRIM_JSON=$(probe_json "$TRIM")
TRIM_V_COUNT=$(echo "$TRIM_JSON" | jq '[.streams[] | select(.codec_type=="video")] | length')
TRIM_A_COUNT=$(echo "$TRIM_JSON" | jq '[.streams[] | select(.codec_type=="audio")] | length')
if [ "$TRIM_V_COUNT" != "1" ] || [ "$TRIM_A_COUNT" != "1" ]; then
  fail "$TRIM" "expected exactly 1 video + 1 audio stream, got ${TRIM_V_COUNT} video + ${TRIM_A_COUNT} audio"
fi
TRIM_SIDE_DATA=$(echo "$TRIM_JSON" | jq '[.streams[] | select(.codec_type=="video") | .side_data_list[]?] | length')
if [ "$TRIM_SIDE_DATA" != "0" ]; then
  fail "$TRIM" "expected no side data (no display matrix), found ${TRIM_SIDE_DATA} entries"
fi
TRIM_CODED_W=$(echo "$TRIM_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .width')
TRIM_CODED_H=$(echo "$TRIM_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .height')
if [ "$TRIM_CODED_W" != "1280" ] || [ "$TRIM_CODED_H" != "720" ]; then
  fail "$TRIM" "expected coded dimensions 1280x720, got ${TRIM_CODED_W}x${TRIM_CODED_H}"
fi
TRIM_FPS_RAW=$(echo "$TRIM_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .avg_frame_rate')
if [ "$TRIM_FPS_RAW" != "30/1" ]; then
  fail "$TRIM" "expected avg_frame_rate 30/1, got ${TRIM_FPS_RAW}"
fi
TRIM_DURATION_S=$(echo "$TRIM_JSON" | jq -r '.format.duration')
TRIM_DURATION_MS=$(awk -v d="$TRIM_DURATION_S" 'BEGIN{printf "%.0f", d*1000}')
TRIM_DURATION_DIFF=$(( TRIM_DURATION_MS - 10000 )); TRIM_DURATION_DIFF=${TRIM_DURATION_DIFF#-}
if [ "$TRIM_DURATION_DIFF" -gt 34 ]; then
  fail "$TRIM" "expected duration within 34ms of 10000ms, got ${TRIM_DURATION_MS}ms"
fi
assert_size "$TRIM" "$TRIM_MAX_BYTES"
echo "OK: $TRIM (coded ${TRIM_CODED_W}x${TRIM_CODED_H}, ${TRIM_FPS_RAW}fps, GOP ${TRIM_GOP}, duration ${TRIM_DURATION_MS}ms, $(stat -c%s "$TRIM") bytes)"

# ---------------------------------------------------------------------------
# Clip G: hdr_hlg10.mp4
# ---------------------------------------------------------------------------
# 10-bit HEVC Main10, HLG (arib-std-b67) transfer, BT.2020 primaries -- Phase 4's first HDR
# fixture (D-01). ffmpeg cannot author Dolby Vision RPU metadata, so the real iPhone/Pixel HDR
# clips stay a reserved slot (see README.md "Reserved slots") until Dan drops them.
#
# High-entropy (mandelbrot) source at ~6Mbps, same reasoning as portrait_hibitrate_1080p60.mp4:
# a low-entropy 10-bit source would encode so small that a later tone-mapped H.264 re-encode of
# it would come out LARGER, tripping the unconditional never-larger substitution and silently
# replacing the tone-map path this phase exists to test with a byte copy of the HDR original.
#
# Four 160x160 pure red/green/blue/white patches at y=40, x=40/240/440/640, constant for the
# whole clip (no time-bucket schedule -- this probe is about colour fidelity, not position in
# time). verify_corpus.sh records their geometry and colour IDENTITY in the hdrProbe sidecar
# block; it cannot record an expected RGB triple because ffmpeg cannot author a reference
# tone-map -- see verify_corpus.sh's HDR_CLIPS handling.
#
# x265 pools=1:frame-threads=1 forces single-threaded, deterministic encoding (the libx264
# clips above get the same guarantee from -threads 1 -x264-params threads=1:sliced_threads=0;
# libx265 has no -threads/-x264-params equivalent, so the determinism knob moves into
# -x265-params instead) -- required because this script's own contract is that two runs
# produce byte-identical clips.
echo "Generating hdr_hlg10.mp4..."

HDR_HLG10=hdr_hlg10.mp4
HDR_HLG10_TMP=hdr_hlg10.tmp.mp4
HDR_HLG10_MAX_BYTES=3000000

ffmpeg -y -loglevel error \
  -f lavfi -i "mandelbrot=size=1280x720:rate=30" \
  -filter_complex "[0:v]drawbox=x=40:y=40:w=160:h=160:color=red:t=fill,drawbox=x=240:y=40:w=160:h=160:color=green:t=fill,drawbox=x=440:y=40:w=160:h=160:color=blue:t=fill,drawbox=x=640:y=40:w=160:h=160:color=white:t=fill[v]" \
  -map "[v]" -an -t 2 \
  -pix_fmt yuv420p10le -c:v libx265 -profile:v main10 \
  -color_primaries bt2020 -color_trc arib-std-b67 -colorspace bt2020nc \
  -x265-params "pools=1:frame-threads=1" \
  -tag:v hvc1 -b:v 6M -maxrate 6M -bufsize 6M \
  "$HDR_HLG10_TMP"

mv "$HDR_HLG10_TMP" "$HDR_HLG10"

HDR_HLG10_JSON=$(probe_json "$HDR_HLG10")
HDR_HLG10_V_COUNT=$(echo "$HDR_HLG10_JSON" | jq '[.streams[] | select(.codec_type=="video")] | length')
HDR_HLG10_A_COUNT=$(echo "$HDR_HLG10_JSON" | jq '[.streams[] | select(.codec_type=="audio")] | length')
if [ "$HDR_HLG10_V_COUNT" != "1" ] || [ "$HDR_HLG10_A_COUNT" != "0" ]; then
  fail "$HDR_HLG10" "expected exactly 1 video + 0 audio stream, got ${HDR_HLG10_V_COUNT} video + ${HDR_HLG10_A_COUNT} audio"
fi
HDR_HLG10_CODEC=$(echo "$HDR_HLG10_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .codec_name')
if [ "$HDR_HLG10_CODEC" != "hevc" ]; then
  fail "$HDR_HLG10" "expected codec_name hevc, got ${HDR_HLG10_CODEC}"
fi
HDR_HLG10_PROFILE=$(echo "$HDR_HLG10_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .profile')
case "$HDR_HLG10_PROFILE" in
  *"Main 10"*) : ;;
  *) fail "$HDR_HLG10" "expected profile containing 'Main 10', got ${HDR_HLG10_PROFILE}" ;;
esac
HDR_HLG10_PIXFMT=$(echo "$HDR_HLG10_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .pix_fmt')
if [ "$HDR_HLG10_PIXFMT" != "yuv420p10le" ]; then
  fail "$HDR_HLG10" "expected pix_fmt yuv420p10le, got ${HDR_HLG10_PIXFMT}"
fi
HDR_HLG10_TRANSFER=$(echo "$HDR_HLG10_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .color_transfer')
if [ "$HDR_HLG10_TRANSFER" != "arib-std-b67" ]; then
  fail "$HDR_HLG10" "expected color_transfer arib-std-b67, got ${HDR_HLG10_TRANSFER}"
fi
HDR_HLG10_PRIMARIES=$(echo "$HDR_HLG10_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .color_primaries')
if [ "$HDR_HLG10_PRIMARIES" != "bt2020" ]; then
  fail "$HDR_HLG10" "expected color_primaries bt2020, got ${HDR_HLG10_PRIMARIES}"
fi
HDR_HLG10_CODED_W=$(echo "$HDR_HLG10_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .width')
HDR_HLG10_CODED_H=$(echo "$HDR_HLG10_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .height')
if [ "$HDR_HLG10_CODED_W" != "1280" ] || [ "$HDR_HLG10_CODED_H" != "720" ]; then
  fail "$HDR_HLG10" "expected coded dimensions 1280x720, got ${HDR_HLG10_CODED_W}x${HDR_HLG10_CODED_H}"
fi
assert_size "$HDR_HLG10" "$HDR_HLG10_MAX_BYTES"
echo "OK: $HDR_HLG10 (hevc Main10, yuv420p10le, arib-std-b67/bt2020, coded ${HDR_HLG10_CODED_W}x${HDR_HLG10_CODED_H}, $(stat -c%s "$HDR_HLG10") bytes)"

# ---------------------------------------------------------------------------
# Clip H: hdr_pq10.mp4
# ---------------------------------------------------------------------------
# Identical geometry, patches and bitrate policy to hdr_hlg10.mp4, but PQ/SMPTE-2084 transfer
# plus mastering-display and max-CLL side data (D-01) -- the x265-params string is verified live
# in 04-RESEARCH.md's "Code Examples".
echo "Generating hdr_pq10.mp4..."

HDR_PQ10=hdr_pq10.mp4
HDR_PQ10_TMP=hdr_pq10.tmp.mp4
HDR_PQ10_MAX_BYTES=3000000

ffmpeg -y -loglevel error \
  -f lavfi -i "mandelbrot=size=1280x720:rate=30" \
  -filter_complex "[0:v]drawbox=x=40:y=40:w=160:h=160:color=red:t=fill,drawbox=x=240:y=40:w=160:h=160:color=green:t=fill,drawbox=x=440:y=40:w=160:h=160:color=blue:t=fill,drawbox=x=640:y=40:w=160:h=160:color=white:t=fill[v]" \
  -map "[v]" -an -t 2 \
  -pix_fmt yuv420p10le -c:v libx265 -profile:v main10 \
  -color_primaries bt2020 -color_trc smpte2084 -colorspace bt2020nc \
  -x265-params "hdr10=1:master-display=G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1):max-cll=1000,400:pools=1:frame-threads=1" \
  -tag:v hvc1 -b:v 6M -maxrate 6M -bufsize 6M \
  "$HDR_PQ10_TMP"

mv "$HDR_PQ10_TMP" "$HDR_PQ10"

HDR_PQ10_JSON=$(probe_json "$HDR_PQ10")
HDR_PQ10_V_COUNT=$(echo "$HDR_PQ10_JSON" | jq '[.streams[] | select(.codec_type=="video")] | length')
HDR_PQ10_A_COUNT=$(echo "$HDR_PQ10_JSON" | jq '[.streams[] | select(.codec_type=="audio")] | length')
if [ "$HDR_PQ10_V_COUNT" != "1" ] || [ "$HDR_PQ10_A_COUNT" != "0" ]; then
  fail "$HDR_PQ10" "expected exactly 1 video + 0 audio stream, got ${HDR_PQ10_V_COUNT} video + ${HDR_PQ10_A_COUNT} audio"
fi
HDR_PQ10_TRANSFER=$(echo "$HDR_PQ10_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .color_transfer')
if [ "$HDR_PQ10_TRANSFER" != "smpte2084" ]; then
  fail "$HDR_PQ10" "expected color_transfer smpte2084, got ${HDR_PQ10_TRANSFER}"
fi
HDR_PQ10_SIDE_DATA=$(ffprobe -v quiet -show_frames -read_intervals '%+#1' -show_entries frame=side_data_list "$HDR_PQ10")
if ! echo "$HDR_PQ10_SIDE_DATA" | grep -q "Mastering display metadata"; then
  fail "$HDR_PQ10" "expected 'Mastering display metadata' side data on the first frame, got: ${HDR_PQ10_SIDE_DATA}"
fi
if ! echo "$HDR_PQ10_SIDE_DATA" | grep -q "Content light level metadata"; then
  fail "$HDR_PQ10" "expected 'Content light level metadata' side data on the first frame, got: ${HDR_PQ10_SIDE_DATA}"
fi
assert_size "$HDR_PQ10" "$HDR_PQ10_MAX_BYTES"
echo "OK: $HDR_PQ10 (hevc Main10, smpte2084/bt2020, mastering-display + max-CLL side data, $(stat -c%s "$HDR_PQ10") bytes)"

# ---------------------------------------------------------------------------
# Clip I: pcm_audio_480p.mov
# ---------------------------------------------------------------------------
# LPCM stereo audio (D-10). 04-RESEARCH.md Pitfall 5/Open Question 4 flagged the container
# choice as unverified end-to-end -- CONFIRMED during this plan's execution: ffmpeg's default
# ISO-MP4 PCM sample entry (`ipcm`, MPEG-4-in-band-PCM's fourcc) round-trips fine through
# ffprobe but Android's MediaExtractor does not surface it as an audio track at all (getMediaInfo
# succeeds but reports hasAudio: false, no exception -- confirmed live on the emulator). A `.mov`
# container makes ffmpeg mux the same pcm_s16le codec under the classic QuickTime `sowt` fourcc
# instead, which MediaExtractor recognizes correctly (also confirmed live). Same codec, only the
# container/fourcc changed -- the pre-authorised contingency from 04-RESEARCH.md, not a new
# decision.
echo "Generating pcm_audio_480p.mov..."

PCM=pcm_audio_480p.mov
PCM_TMP=pcm_audio_480p.tmp.mov

ffmpeg -y -loglevel error \
  -f lavfi -i "testsrc=size=854x480:rate=30:duration=2" \
  -f lavfi -i "sine=frequency=440:sample_rate=48000:duration=2" \
  -map 0:v -map 1:a \
  -c:v libx264 -pix_fmt yuv420p -preset veryfast -crf 30 \
  -threads 1 -x264-params threads=1:sliced_threads=0 \
  -c:a pcm_s16le -ac 2 -ar 48000 \
  -shortest \
  "$PCM_TMP"

mv "$PCM_TMP" "$PCM"

PCM_JSON=$(probe_json "$PCM")
PCM_V_COUNT=$(echo "$PCM_JSON" | jq '[.streams[] | select(.codec_type=="video")] | length')
PCM_A_COUNT=$(echo "$PCM_JSON" | jq '[.streams[] | select(.codec_type=="audio")] | length')
if [ "$PCM_V_COUNT" != "1" ] || [ "$PCM_A_COUNT" != "1" ]; then
  fail "$PCM" "expected exactly 1 video + 1 audio stream, got ${PCM_V_COUNT} video + ${PCM_A_COUNT} audio"
fi
PCM_AUDIO_CODEC=$(echo "$PCM_JSON" | jq -r '.streams[] | select(.codec_type=="audio") | .codec_name')
if [ "$PCM_AUDIO_CODEC" != "pcm_s16le" ]; then
  fail "$PCM" "expected audio codec_name pcm_s16le, got ${PCM_AUDIO_CODEC}"
fi
PCM_AUDIO_TAG=$(echo "$PCM_JSON" | jq -r '.streams[] | select(.codec_type=="audio") | .codec_tag_string')
if [ "$PCM_AUDIO_TAG" != "sowt" ]; then
  fail "$PCM" "expected the QuickTime 'sowt' PCM sample entry (the reason this fixture is a .mov, not a .mp4), got codec_tag_string ${PCM_AUDIO_TAG}"
fi
assert_size "$PCM" "$DEFAULT_MAX_BYTES"
echo "OK: $PCM (1 video + 1 pcm_s16le/sowt audio, $(stat -c%s "$PCM") bytes)"

# ---------------------------------------------------------------------------
# Clip J: surround51_480p.mp4
# ---------------------------------------------------------------------------
# 6-channel (5.1) AAC audio built with the pan=5.1 filter graph (D-09).
echo "Generating surround51_480p.mp4..."

SURROUND=surround51_480p.mp4
SURROUND_TMP=surround51_480p.tmp.mp4

ffmpeg -y -loglevel error \
  -f lavfi -i "testsrc=size=854x480:rate=30:duration=2" \
  -f lavfi -i "sine=frequency=440:sample_rate=48000:duration=2" \
  -filter_complex "[1:a]pan=5.1|c0=c0|c1=c0|c2=c0|c3=c0|c4=c0|c5=c0[a51]" \
  -map 0:v -map "[a51]" \
  -c:v libx264 -pix_fmt yuv420p -preset veryfast -crf 30 \
  -threads 1 -x264-params threads=1:sliced_threads=0 \
  -c:a aac -b:a 384k \
  -shortest \
  "$SURROUND_TMP"

mv "$SURROUND_TMP" "$SURROUND"

SURROUND_JSON=$(probe_json "$SURROUND")
SURROUND_V_COUNT=$(echo "$SURROUND_JSON" | jq '[.streams[] | select(.codec_type=="video")] | length')
SURROUND_A_COUNT=$(echo "$SURROUND_JSON" | jq '[.streams[] | select(.codec_type=="audio")] | length')
if [ "$SURROUND_V_COUNT" != "1" ] || [ "$SURROUND_A_COUNT" != "1" ]; then
  fail "$SURROUND" "expected exactly 1 video + 1 audio stream, got ${SURROUND_V_COUNT} video + ${SURROUND_A_COUNT} audio"
fi
SURROUND_CHANNELS=$(echo "$SURROUND_JSON" | jq -r '.streams[] | select(.codec_type=="audio") | .channels')
SURROUND_LAYOUT=$(echo "$SURROUND_JSON" | jq -r '.streams[] | select(.codec_type=="audio") | .channel_layout')
SURROUND_CODEC=$(echo "$SURROUND_JSON" | jq -r '.streams[] | select(.codec_type=="audio") | .codec_name')
if [ "$SURROUND_CHANNELS" != "6" ] || [ "$SURROUND_LAYOUT" != "5.1" ] || [ "$SURROUND_CODEC" != "aac" ]; then
  fail "$SURROUND" "expected 6-channel 5.1 aac audio, got ${SURROUND_CHANNELS}ch ${SURROUND_LAYOUT} ${SURROUND_CODEC}"
fi
assert_size "$SURROUND" "$DEFAULT_MAX_BYTES"
echo "OK: $SURROUND (1 video + 6-channel 5.1 aac audio, $(stat -c%s "$SURROUND") bytes)"

# ---------------------------------------------------------------------------
# Clip K: uhd_4k60.mp4
# ---------------------------------------------------------------------------
# 3840x2160 at 60fps, no audio (D-12). High-entropy (mandelbrot) source, same never-larger
# reasoning as hdr_hlg10.mp4/portrait_hibitrate_1080p60.mp4: a low-entropy source would encode
# too small for a later re-encode to shrink further.
echo "Generating uhd_4k60.mp4..."

UHD=uhd_4k60.mp4
UHD_TMP=uhd_4k60.tmp.mp4
UHD_MAX_BYTES=3000000

ffmpeg -y -loglevel error \
  -f lavfi -i "mandelbrot=size=3840x2160:rate=60" \
  -an -t 2 \
  -c:v libx264 -pix_fmt yuv420p -preset veryfast -b:v 6M -maxrate 6M -bufsize 3M \
  -threads 1 -x264-params threads=1:sliced_threads=0 \
  "$UHD_TMP"

mv "$UHD_TMP" "$UHD"

UHD_JSON=$(probe_json "$UHD")
UHD_V_COUNT=$(echo "$UHD_JSON" | jq '[.streams[] | select(.codec_type=="video")] | length')
UHD_A_COUNT=$(echo "$UHD_JSON" | jq '[.streams[] | select(.codec_type=="audio")] | length')
if [ "$UHD_V_COUNT" != "1" ] || [ "$UHD_A_COUNT" != "0" ]; then
  fail "$UHD" "expected exactly 1 video + 0 audio stream, got ${UHD_V_COUNT} video + ${UHD_A_COUNT} audio"
fi
UHD_CODED_W=$(echo "$UHD_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .width')
UHD_CODED_H=$(echo "$UHD_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .height')
if [ "$UHD_CODED_W" != "3840" ] || [ "$UHD_CODED_H" != "2160" ]; then
  fail "$UHD" "expected coded dimensions 3840x2160, got ${UHD_CODED_W}x${UHD_CODED_H}"
fi
UHD_FPS_RAW=$(echo "$UHD_JSON" | jq -r '.streams[] | select(.codec_type=="video") | .avg_frame_rate')
UHD_FPS=$(awk -F/ -v r="$UHD_FPS_RAW" 'BEGIN{split(r,a,"/"); if (a[2]+0==0) print "0"; else printf "%.0f", a[1]/a[2]}')
if [ "$UHD_FPS" != "60" ]; then
  fail "$UHD" "expected avg frame rate 60, got ${UHD_FPS_RAW} (~${UHD_FPS})"
fi
assert_size "$UHD" "$UHD_MAX_BYTES"
echo "OK: $UHD (coded ${UHD_CODED_W}x${UHD_CODED_H}, ${UHD_FPS}fps, no audio, $(stat -c%s "$UHD") bytes)"

echo "All corpus clips generated and self-verified."
