// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class CompressVideoError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "CompressVideoError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? CompressVideoError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// The wire-format media info message returned by [ProbeHostApi.getMediaInfo].
///
/// This is the generated, private counterpart of the public, hand-written `MediaInfo`
/// class in `lib/src/media_info.dart` — see that file for the documented public API.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MediaInfoMessage: Hashable, CustomStringConvertible {
  /// Duration of the media, in milliseconds.
  var durationMs: Int64
  /// Displayed (rotation-corrected) width, in pixels. Never the coded, pre-rotation width.
  var widthPx: Int64
  /// Displayed (rotation-corrected) height, in pixels. Never the coded, pre-rotation height.
  var heightPx: Int64
  /// Unsigned clockwise rotation, in degrees, as reported by the platform before the
  /// correction that produced [widthPx]/[heightPx] was applied. `0` for an unrotated clip.
  var rotationDegrees: Int64
  /// Size of the underlying file, in bytes.
  var sizeBytes: Int64
  /// Normalised video codec token (`h264`, `hevc`, `av1`, `vp9`, `unknown`), or `null` when
  /// the platform could not determine it. `null` is the sentinel for unknown — never an
  /// empty string.
  var videoCodec: String? = nil
  /// Average video-track bitrate, in bits per second, or `null` when the platform could not
  /// determine it. `null` is the sentinel for unknown — never `0`.
  var videoBitrateBps: Int64? = nil
  /// Video frame rate, in frames per second, or `null` when the platform could not determine
  /// it. `null` is the sentinel for unknown — never `0`. Never rounded to an integer.
  var frameRateFps: Double? = nil
  /// Whether the media has at least one audio track.
  var hasAudio: Bool
  /// Whether the video is HDR (PQ or HLG transfer characteristic). `false` when the running
  /// platform cannot determine HDR status — never an exception.
  var isHdr: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaInfoMessage? {
    let durationMs = pigeonVar_list[0] as! Int64
    let widthPx = pigeonVar_list[1] as! Int64
    let heightPx = pigeonVar_list[2] as! Int64
    let rotationDegrees = pigeonVar_list[3] as! Int64
    let sizeBytes = pigeonVar_list[4] as! Int64
    let videoCodec: String? = nilOrValue(pigeonVar_list[5])
    let videoBitrateBps: Int64? = nilOrValue(pigeonVar_list[6])
    let frameRateFps: Double? = nilOrValue(pigeonVar_list[7])
    let hasAudio = pigeonVar_list[8] as! Bool
    let isHdr = pigeonVar_list[9] as! Bool

    return MediaInfoMessage(
      durationMs: durationMs,
      widthPx: widthPx,
      heightPx: heightPx,
      rotationDegrees: rotationDegrees,
      sizeBytes: sizeBytes,
      videoCodec: videoCodec,
      videoBitrateBps: videoBitrateBps,
      frameRateFps: frameRateFps,
      hasAudio: hasAudio,
      isHdr: isHdr
    )
  }
  func toList() -> [Any?] {
    return [
      durationMs,
      widthPx,
      heightPx,
      rotationDegrees,
      sizeBytes,
      videoCodec,
      videoBitrateBps,
      frameRateFps,
      hasAudio,
      isHdr,
    ]
  }
  static func == (lhs: MediaInfoMessage, rhs: MediaInfoMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs) && MessagesPigeonInternal.deepEquals(lhs.widthPx, rhs.widthPx) && MessagesPigeonInternal.deepEquals(lhs.heightPx, rhs.heightPx) && MessagesPigeonInternal.deepEquals(lhs.rotationDegrees, rhs.rotationDegrees) && MessagesPigeonInternal.deepEquals(lhs.sizeBytes, rhs.sizeBytes) && MessagesPigeonInternal.deepEquals(lhs.videoCodec, rhs.videoCodec) && MessagesPigeonInternal.deepEquals(lhs.videoBitrateBps, rhs.videoBitrateBps) && MessagesPigeonInternal.deepEquals(lhs.frameRateFps, rhs.frameRateFps) && MessagesPigeonInternal.deepEquals(lhs.hasAudio, rhs.hasAudio) && MessagesPigeonInternal.deepEquals(lhs.isHdr, rhs.isHdr)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MediaInfoMessage")
    MessagesPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: widthPx, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: heightPx, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rotationDegrees, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sizeBytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: videoCodec, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: videoBitrateBps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: frameRateFps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: hasAudio, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isHdr, hasher: &hasher)
  }

  public var description: String {
    return "MediaInfoMessage(durationMs: \(String(describing: durationMs)), widthPx: \(String(describing: widthPx)), heightPx: \(String(describing: heightPx)), rotationDegrees: \(String(describing: rotationDegrees)), sizeBytes: \(String(describing: sizeBytes)), videoCodec: \(String(describing: videoCodec)), videoBitrateBps: \(String(describing: videoBitrateBps)), frameRateFps: \(String(describing: frameRateFps)), hasAudio: \(String(describing: hasAudio)), isHdr: \(String(describing: isHdr)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return MediaInfoMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? MediaInfoMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Reads media info from a file. Implemented on every platform in this phase.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ProbeHostApi {
  /// Returns the [MediaInfoMessage] for the media at [path].
  ///
  /// Declared here in full for the whole contract; only the Android implementation lands in
  /// this plan. Failures throw `CompressVideoError` with the [path] never logged or included
  /// in any diagnostic output outside the returned error detail.
  func getMediaInfo(path: String) async throws -> MediaInfoMessage
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ProbeHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ProbeHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ProbeHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Returns the [MediaInfoMessage] for the media at [path].
    ///
    /// Declared here in full for the whole contract; only the Android implementation lands in
    /// this plan. Failures throw `CompressVideoError` with the [path] never logged or included
    /// in any diagnostic output outside the returned error detail.
    let getMediaInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.compress_video.ProbeHostApi.getMediaInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMediaInfoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.getMediaInfo(path: pathArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getMediaInfoChannel.setMessageHandler(nil)
    }
  }
}
/// Generates poster-frame thumbnails from a file. Declared here for contract completeness;
/// no platform implements this yet — that lands in a later plan in this phase.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ThumbnailHostApi {
  /// Returns JPEG-encoded thumbnail bytes for the frame at [positionMs] in the media at
  /// [path], encoded at [quality] (1-100), with the longer side capped at [maxDimensionPx]
  /// when non-null (never upscaled).
  func getThumbnail(path: String, positionMs: Int64, quality: Int64, maxDimensionPx: Int64?) async throws -> FlutterStandardTypedData
  /// Same as [getThumbnail], but writes the JPEG to a file and returns its path. Writes to a
  /// unique name in the app cache directory, or to [outputPath] when given.
  func getThumbnailFile(path: String, positionMs: Int64, quality: Int64, maxDimensionPx: Int64?, outputPath: String?) async throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ThumbnailHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ThumbnailHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ThumbnailHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Returns JPEG-encoded thumbnail bytes for the frame at [positionMs] in the media at
    /// [path], encoded at [quality] (1-100), with the longer side capped at [maxDimensionPx]
    /// when non-null (never upscaled).
    let getThumbnailChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.compress_video.ThumbnailHostApi.getThumbnail\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getThumbnailChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let positionMsArg = args[1] as! Int64
        let qualityArg = args[2] as! Int64
        let maxDimensionPxArg: Int64? = nilOrValue(args[3])
        Task { @MainActor in
          do {
            let result = try await api.getThumbnail(path: pathArg, positionMs: positionMsArg, quality: qualityArg, maxDimensionPx: maxDimensionPxArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getThumbnailChannel.setMessageHandler(nil)
    }
    /// Same as [getThumbnail], but writes the JPEG to a file and returns its path. Writes to a
    /// unique name in the app cache directory, or to [outputPath] when given.
    let getThumbnailFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.compress_video.ThumbnailHostApi.getThumbnailFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getThumbnailFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let positionMsArg = args[1] as! Int64
        let qualityArg = args[2] as! Int64
        let maxDimensionPxArg: Int64? = nilOrValue(args[3])
        let outputPathArg: String? = nilOrValue(args[4])
        Task { @MainActor in
          do {
            let result = try await api.getThumbnailFile(path: pathArg, positionMs: positionMsArg, quality: qualityArg, maxDimensionPx: maxDimensionPxArg, outputPath: outputPathArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getThumbnailFileChannel.setMessageHandler(nil)
    }
  }
}
