// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class CompressVideoError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "CompressVideoError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? CompressVideoError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> CompressVideoError {
  return CompressVideoError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// How the audio track is handled during compression. Wire-level counterpart of the public
/// `AudioMode` enum in `lib/src/compress_options.dart`.
enum AudioModeMessage: Int, CaseIterable {
  /// Keep the source audio track's encoding when it is already MP4-compatible AAC; re-encode
  /// otherwise. This is the default.
  case passthrough = 0
  /// Always re-encode the audio track to AAC, honouring the requested bitrate and channels.
  case reencode = 1
  /// Remove the audio track entirely. The result's `audioCodec` is `null`.
  case strip = 2
}

/// The wire-format media info message returned by [ProbeHostApi.getMediaInfo].
///
/// This is the generated, private counterpart of the public, hand-written `MediaInfo`
/// class in `lib/src/media_info.dart` — see that file for the documented public API.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MediaInfoMessage: Hashable, CustomStringConvertible {
  /// Duration of the media, in milliseconds.
  var durationMs: Int64
  /// Displayed (rotation-corrected) width, in pixels. Never the coded, pre-rotation width.
  var widthPx: Int64
  /// Displayed (rotation-corrected) height, in pixels. Never the coded, pre-rotation height.
  var heightPx: Int64
  /// Unsigned clockwise rotation, in degrees, as reported by the platform before the
  /// correction that produced [widthPx]/[heightPx] was applied. `0` for an unrotated clip.
  var rotationDegrees: Int64
  /// Size of the underlying file, in bytes.
  var sizeBytes: Int64
  /// Normalised video codec token (`h264`, `hevc`, `av1`, `vp9`, `unknown`), or `null` when
  /// the platform could not determine it. `null` is the sentinel for unknown — never an
  /// empty string.
  var videoCodec: String? = nil
  /// Average video-track bitrate, in bits per second, or `null` when the platform could not
  /// determine it. `null` is the sentinel for unknown — never `0`.
  var videoBitrateBps: Int64? = nil
  /// Video frame rate, in frames per second, or `null` when the platform could not determine
  /// it. `null` is the sentinel for unknown — never `0`. Never rounded to an integer.
  var frameRateFps: Double? = nil
  /// Whether the media has at least one audio track.
  var hasAudio: Bool
  /// Whether the video is HDR (PQ or HLG transfer characteristic). `false` when the running
  /// platform cannot determine HDR status — never an exception.
  var isHdr: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaInfoMessage? {
    let durationMs = pigeonVar_list[0] as! Int64
    let widthPx = pigeonVar_list[1] as! Int64
    let heightPx = pigeonVar_list[2] as! Int64
    let rotationDegrees = pigeonVar_list[3] as! Int64
    let sizeBytes = pigeonVar_list[4] as! Int64
    let videoCodec: String? = nilOrValue(pigeonVar_list[5])
    let videoBitrateBps: Int64? = nilOrValue(pigeonVar_list[6])
    let frameRateFps: Double? = nilOrValue(pigeonVar_list[7])
    let hasAudio = pigeonVar_list[8] as! Bool
    let isHdr = pigeonVar_list[9] as! Bool

    return MediaInfoMessage(
      durationMs: durationMs,
      widthPx: widthPx,
      heightPx: heightPx,
      rotationDegrees: rotationDegrees,
      sizeBytes: sizeBytes,
      videoCodec: videoCodec,
      videoBitrateBps: videoBitrateBps,
      frameRateFps: frameRateFps,
      hasAudio: hasAudio,
      isHdr: isHdr
    )
  }
  func toList() -> [Any?] {
    return [
      durationMs,
      widthPx,
      heightPx,
      rotationDegrees,
      sizeBytes,
      videoCodec,
      videoBitrateBps,
      frameRateFps,
      hasAudio,
      isHdr,
    ]
  }
  static func == (lhs: MediaInfoMessage, rhs: MediaInfoMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs) && MessagesPigeonInternal.deepEquals(lhs.widthPx, rhs.widthPx) && MessagesPigeonInternal.deepEquals(lhs.heightPx, rhs.heightPx) && MessagesPigeonInternal.deepEquals(lhs.rotationDegrees, rhs.rotationDegrees) && MessagesPigeonInternal.deepEquals(lhs.sizeBytes, rhs.sizeBytes) && MessagesPigeonInternal.deepEquals(lhs.videoCodec, rhs.videoCodec) && MessagesPigeonInternal.deepEquals(lhs.videoBitrateBps, rhs.videoBitrateBps) && MessagesPigeonInternal.deepEquals(lhs.frameRateFps, rhs.frameRateFps) && MessagesPigeonInternal.deepEquals(lhs.hasAudio, rhs.hasAudio) && MessagesPigeonInternal.deepEquals(lhs.isHdr, rhs.isHdr)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MediaInfoMessage")
    MessagesPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: widthPx, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: heightPx, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rotationDegrees, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sizeBytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: videoCodec, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: videoBitrateBps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: frameRateFps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: hasAudio, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isHdr, hasher: &hasher)
  }

  public var description: String {
    return "MediaInfoMessage(durationMs: \(String(describing: durationMs)), widthPx: \(String(describing: widthPx)), heightPx: \(String(describing: heightPx)), rotationDegrees: \(String(describing: rotationDegrees)), sizeBytes: \(String(describing: sizeBytes)), videoCodec: \(String(describing: videoCodec)), videoBitrateBps: \(String(describing: videoBitrateBps)), frameRateFps: \(String(describing: frameRateFps)), hasAudio: \(String(describing: hasAudio)), isHdr: \(String(describing: isHdr)))"
  }
}

/// A compression request, sent once per job via [CompressHostApi.startCompress] and also used
/// (identically) by [CompressHostApi.estimate] to predict what that request would produce.
///
/// The preset named by the caller's `CompressOptions.preset` (see
/// `lib/src/compress_options.dart`) is resolved to a concrete [maxLongSidePx] plus
/// [videoBitrateBps] entirely on the Dart side before this message is built — no preset enum
/// crosses the channel, so a reader will not find one here.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CompressRequestMessage: Hashable, CustomStringConvertible {
  /// Explicit cap on the output's longer displayed side, in pixels, or `null` when the caller
  /// did not set `CompressOptions.maxLongSidePx` -- in which case `SizeGuard` falls back to
  /// [presetMaxLongSidePx]. Never the preset's own value pre-resolved into this field (that
  /// was 02-02's tracer-only shape); this field is `null` unless the caller explicitly set it,
  /// which is what lets the native side tell "explicit override" apart from "use the preset".
  var maxLongSidePx: Int64? = nil
  /// Explicit target video bitrate, in bits per second, or `null` when the caller did not set
  /// `CompressOptions.videoBitrateBps` -- in which case `SizeGuard` resolves it from
  /// [targetSizeMb] if set, else scales [presetVideoBitrateBps] by the actual output
  /// resolution and frame rate (SizeGuard.kt rule 6; this is the fix for the incumbent's
  /// fixed-bitrate-regardless-of-resolution defect, PITFALLS.md row 13).
  var videoBitrateBps: Int64? = nil
  /// Target output file size, in megabytes, or `null` when no target size was requested.
  var targetSizeMb: Double? = nil
  /// The selected `CompressPreset`'s own nominal long-side cap, in pixels, always sent
  /// regardless of any [maxLongSidePx] override -- the reference value SizeGuard's bitrate
  /// scaling formula divides by. The preset enum itself never crosses the channel (02-02
  /// decision, unchanged); only its two resolved numbers do.
  var presetMaxLongSidePx: Int64
  /// The selected `CompressPreset`'s own nominal video bitrate, in bits per second, always
  /// sent regardless of any [videoBitrateBps] override -- the reference value SizeGuard scales
  /// when neither an explicit bitrate nor a [targetSizeMb] was requested.
  var presetVideoBitrateBps: Int64
  /// Cap on the output's frame rate, in frames per second. Never upscales the input's own
  /// frame rate — the effective cap is `min(maxFps, input fps)`.
  var maxFps: Int64
  /// How the audio track is handled. See [AudioModeMessage].
  var audioMode: AudioModeMessage
  /// Target audio bitrate, in bits per second, when [audioMode] is
  /// [AudioModeMessage.reencode]. `null` otherwise.
  var audioBitrateBps: Int64? = nil
  /// Target audio channel count, when [audioMode] is [AudioModeMessage.reencode]. `null`
  /// otherwise.
  var audioChannels: Int64? = nil
  /// Start of the trim range, in milliseconds from the start of the input, or `null` for no
  /// trim start.
  var trimStartMs: Int64? = nil
  /// End of the trim range, in milliseconds from the start of the input, or `null` for no
  /// trim end.
  var trimEndMs: Int64? = nil
  /// Destination path for the compressed output, or `null` to use the plugin's own cache
  /// directory with a name derived from the job id.
  var outputPath: String? = nil
  /// Requested output video codec. Only `"h264"` is accepted in this phase; HEVC opt-in is
  /// Phase 4.
  var videoCodec: String
  /// Requested HDR handling. Only `"toneMapToSdr"` is accepted in this phase; keep-HDR opt-in
  /// is Phase 4.
  var hdrMode: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CompressRequestMessage? {
    let maxLongSidePx: Int64? = nilOrValue(pigeonVar_list[0])
    let videoBitrateBps: Int64? = nilOrValue(pigeonVar_list[1])
    let targetSizeMb: Double? = nilOrValue(pigeonVar_list[2])
    let presetMaxLongSidePx = pigeonVar_list[3] as! Int64
    let presetVideoBitrateBps = pigeonVar_list[4] as! Int64
    let maxFps = pigeonVar_list[5] as! Int64
    let audioMode = pigeonVar_list[6] as! AudioModeMessage
    let audioBitrateBps: Int64? = nilOrValue(pigeonVar_list[7])
    let audioChannels: Int64? = nilOrValue(pigeonVar_list[8])
    let trimStartMs: Int64? = nilOrValue(pigeonVar_list[9])
    let trimEndMs: Int64? = nilOrValue(pigeonVar_list[10])
    let outputPath: String? = nilOrValue(pigeonVar_list[11])
    let videoCodec = pigeonVar_list[12] as! String
    let hdrMode = pigeonVar_list[13] as! String

    return CompressRequestMessage(
      maxLongSidePx: maxLongSidePx,
      videoBitrateBps: videoBitrateBps,
      targetSizeMb: targetSizeMb,
      presetMaxLongSidePx: presetMaxLongSidePx,
      presetVideoBitrateBps: presetVideoBitrateBps,
      maxFps: maxFps,
      audioMode: audioMode,
      audioBitrateBps: audioBitrateBps,
      audioChannels: audioChannels,
      trimStartMs: trimStartMs,
      trimEndMs: trimEndMs,
      outputPath: outputPath,
      videoCodec: videoCodec,
      hdrMode: hdrMode
    )
  }
  func toList() -> [Any?] {
    return [
      maxLongSidePx,
      videoBitrateBps,
      targetSizeMb,
      presetMaxLongSidePx,
      presetVideoBitrateBps,
      maxFps,
      audioMode,
      audioBitrateBps,
      audioChannels,
      trimStartMs,
      trimEndMs,
      outputPath,
      videoCodec,
      hdrMode,
    ]
  }
  static func == (lhs: CompressRequestMessage, rhs: CompressRequestMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.maxLongSidePx, rhs.maxLongSidePx) && MessagesPigeonInternal.deepEquals(lhs.videoBitrateBps, rhs.videoBitrateBps) && MessagesPigeonInternal.deepEquals(lhs.targetSizeMb, rhs.targetSizeMb) && MessagesPigeonInternal.deepEquals(lhs.presetMaxLongSidePx, rhs.presetMaxLongSidePx) && MessagesPigeonInternal.deepEquals(lhs.presetVideoBitrateBps, rhs.presetVideoBitrateBps) && MessagesPigeonInternal.deepEquals(lhs.maxFps, rhs.maxFps) && MessagesPigeonInternal.deepEquals(lhs.audioMode, rhs.audioMode) && MessagesPigeonInternal.deepEquals(lhs.audioBitrateBps, rhs.audioBitrateBps) && MessagesPigeonInternal.deepEquals(lhs.audioChannels, rhs.audioChannels) && MessagesPigeonInternal.deepEquals(lhs.trimStartMs, rhs.trimStartMs) && MessagesPigeonInternal.deepEquals(lhs.trimEndMs, rhs.trimEndMs) && MessagesPigeonInternal.deepEquals(lhs.outputPath, rhs.outputPath) && MessagesPigeonInternal.deepEquals(lhs.videoCodec, rhs.videoCodec) && MessagesPigeonInternal.deepEquals(lhs.hdrMode, rhs.hdrMode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CompressRequestMessage")
    MessagesPigeonInternal.deepHash(value: maxLongSidePx, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: videoBitrateBps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: targetSizeMb, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: presetMaxLongSidePx, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: presetVideoBitrateBps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxFps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: audioMode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: audioBitrateBps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: audioChannels, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: trimStartMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: trimEndMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: outputPath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: videoCodec, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: hdrMode, hasher: &hasher)
  }

  public var description: String {
    return "CompressRequestMessage(maxLongSidePx: \(String(describing: maxLongSidePx)), videoBitrateBps: \(String(describing: videoBitrateBps)), targetSizeMb: \(String(describing: targetSizeMb)), presetMaxLongSidePx: \(String(describing: presetMaxLongSidePx)), presetVideoBitrateBps: \(String(describing: presetVideoBitrateBps)), maxFps: \(String(describing: maxFps)), audioMode: \(String(describing: audioMode)), audioBitrateBps: \(String(describing: audioBitrateBps)), audioChannels: \(String(describing: audioChannels)), trimStartMs: \(String(describing: trimStartMs)), trimEndMs: \(String(describing: trimEndMs)), outputPath: \(String(describing: outputPath)), videoCodec: \(String(describing: videoCodec)), hdrMode: \(String(describing: hdrMode)))"
  }
}

/// The typed result of a completed compression job. Every field is populated from a re-probe
/// of the finished output file, never from the export engine's own approximate fields — see
/// 02-RESEARCH.md Pitfall 4.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CompressResultMessage: Hashable, CustomStringConvertible {
  /// Absolute path to the compressed output file.
  var outputPath: String
  /// Size of the input file, in bytes.
  var inputBytes: Int64
  /// Size of the output file, in bytes.
  var outputBytes: Int64
  /// Displayed (rotation-corrected) width of the output, in pixels.
  var widthPx: Int64
  /// Displayed (rotation-corrected) height of the output, in pixels.
  var heightPx: Int64
  /// Duration of the output, in milliseconds, from a re-probe of the finished file.
  var durationMs: Int64
  /// Normalised video codec of the output (for example `h264`).
  var videoCodec: String
  /// Normalised audio codec of the output, or `null` when the audio track was stripped or the
  /// source had none.
  var audioCodec: String? = nil
  /// Whether the job ran as a transmux (container remux with no video re-encode) rather than
  /// a full encode.
  var transmuxed: Bool
  /// Whether the original input bytes were copied to [outputPath] because compressing would
  /// have produced an equal-or-larger file. `outputPath` always names a file the plugin owns
  /// (never the caller's original input path) when this is `true`.
  var usedOriginal: Bool
  /// Reserved for Phase 4's HDR tone-mapping. Always `false` in this phase.
  var toneMapped: Bool
  /// Reserved for Phase 4's HEVC hardware-fallback handling. Always `false` in this phase.
  var hevcFallback: Bool
  /// Whether the audio track was re-encoded (as opposed to passed through or stripped).
  var audioReencoded: Bool
  /// Wall-clock time the compression took, in milliseconds.
  var elapsedMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CompressResultMessage? {
    let outputPath = pigeonVar_list[0] as! String
    let inputBytes = pigeonVar_list[1] as! Int64
    let outputBytes = pigeonVar_list[2] as! Int64
    let widthPx = pigeonVar_list[3] as! Int64
    let heightPx = pigeonVar_list[4] as! Int64
    let durationMs = pigeonVar_list[5] as! Int64
    let videoCodec = pigeonVar_list[6] as! String
    let audioCodec: String? = nilOrValue(pigeonVar_list[7])
    let transmuxed = pigeonVar_list[8] as! Bool
    let usedOriginal = pigeonVar_list[9] as! Bool
    let toneMapped = pigeonVar_list[10] as! Bool
    let hevcFallback = pigeonVar_list[11] as! Bool
    let audioReencoded = pigeonVar_list[12] as! Bool
    let elapsedMs = pigeonVar_list[13] as! Int64

    return CompressResultMessage(
      outputPath: outputPath,
      inputBytes: inputBytes,
      outputBytes: outputBytes,
      widthPx: widthPx,
      heightPx: heightPx,
      durationMs: durationMs,
      videoCodec: videoCodec,
      audioCodec: audioCodec,
      transmuxed: transmuxed,
      usedOriginal: usedOriginal,
      toneMapped: toneMapped,
      hevcFallback: hevcFallback,
      audioReencoded: audioReencoded,
      elapsedMs: elapsedMs
    )
  }
  func toList() -> [Any?] {
    return [
      outputPath,
      inputBytes,
      outputBytes,
      widthPx,
      heightPx,
      durationMs,
      videoCodec,
      audioCodec,
      transmuxed,
      usedOriginal,
      toneMapped,
      hevcFallback,
      audioReencoded,
      elapsedMs,
    ]
  }
  static func == (lhs: CompressResultMessage, rhs: CompressResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.outputPath, rhs.outputPath) && MessagesPigeonInternal.deepEquals(lhs.inputBytes, rhs.inputBytes) && MessagesPigeonInternal.deepEquals(lhs.outputBytes, rhs.outputBytes) && MessagesPigeonInternal.deepEquals(lhs.widthPx, rhs.widthPx) && MessagesPigeonInternal.deepEquals(lhs.heightPx, rhs.heightPx) && MessagesPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs) && MessagesPigeonInternal.deepEquals(lhs.videoCodec, rhs.videoCodec) && MessagesPigeonInternal.deepEquals(lhs.audioCodec, rhs.audioCodec) && MessagesPigeonInternal.deepEquals(lhs.transmuxed, rhs.transmuxed) && MessagesPigeonInternal.deepEquals(lhs.usedOriginal, rhs.usedOriginal) && MessagesPigeonInternal.deepEquals(lhs.toneMapped, rhs.toneMapped) && MessagesPigeonInternal.deepEquals(lhs.hevcFallback, rhs.hevcFallback) && MessagesPigeonInternal.deepEquals(lhs.audioReencoded, rhs.audioReencoded) && MessagesPigeonInternal.deepEquals(lhs.elapsedMs, rhs.elapsedMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CompressResultMessage")
    MessagesPigeonInternal.deepHash(value: outputPath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: inputBytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: outputBytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: widthPx, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: heightPx, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: videoCodec, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: audioCodec, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: transmuxed, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: usedOriginal, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: toneMapped, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: hevcFallback, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: audioReencoded, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: elapsedMs, hasher: &hasher)
  }

  public var description: String {
    return "CompressResultMessage(outputPath: \(String(describing: outputPath)), inputBytes: \(String(describing: inputBytes)), outputBytes: \(String(describing: outputBytes)), widthPx: \(String(describing: widthPx)), heightPx: \(String(describing: heightPx)), durationMs: \(String(describing: durationMs)), videoCodec: \(String(describing: videoCodec)), audioCodec: \(String(describing: audioCodec)), transmuxed: \(String(describing: transmuxed)), usedOriginal: \(String(describing: usedOriginal)), toneMapped: \(String(describing: toneMapped)), hevcFallback: \(String(describing: hevcFallback)), audioReencoded: \(String(describing: audioReencoded)), elapsedMs: \(String(describing: elapsedMs)))"
  }
}

/// The typed, pre-flight prediction of what a [CompressRequestMessage] would produce, without
/// running an actual encode.
///
/// Generated class from Pigeon that represents data sent in messages.
struct EstimateMessage: Hashable, CustomStringConvertible {
  /// Predicted size of the output, in bytes.
  var outputBytes: Int64
  /// Predicted duration of the output, in milliseconds.
  var durationMs: Int64
  /// Predicted displayed width of the output, in pixels.
  var widthPx: Int64
  /// Predicted displayed height of the output, in pixels.
  var heightPx: Int64
  /// Whether the request would run as a transmux rather than a full encode.
  var wouldTransmux: Bool
  /// Whether the request would fall back to copying the original input rather than encoding.
  var wouldUseOriginal: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EstimateMessage? {
    let outputBytes = pigeonVar_list[0] as! Int64
    let durationMs = pigeonVar_list[1] as! Int64
    let widthPx = pigeonVar_list[2] as! Int64
    let heightPx = pigeonVar_list[3] as! Int64
    let wouldTransmux = pigeonVar_list[4] as! Bool
    let wouldUseOriginal = pigeonVar_list[5] as! Bool

    return EstimateMessage(
      outputBytes: outputBytes,
      durationMs: durationMs,
      widthPx: widthPx,
      heightPx: heightPx,
      wouldTransmux: wouldTransmux,
      wouldUseOriginal: wouldUseOriginal
    )
  }
  func toList() -> [Any?] {
    return [
      outputBytes,
      durationMs,
      widthPx,
      heightPx,
      wouldTransmux,
      wouldUseOriginal,
    ]
  }
  static func == (lhs: EstimateMessage, rhs: EstimateMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.outputBytes, rhs.outputBytes) && MessagesPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs) && MessagesPigeonInternal.deepEquals(lhs.widthPx, rhs.widthPx) && MessagesPigeonInternal.deepEquals(lhs.heightPx, rhs.heightPx) && MessagesPigeonInternal.deepEquals(lhs.wouldTransmux, rhs.wouldTransmux) && MessagesPigeonInternal.deepEquals(lhs.wouldUseOriginal, rhs.wouldUseOriginal)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("EstimateMessage")
    MessagesPigeonInternal.deepHash(value: outputBytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: widthPx, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: heightPx, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: wouldTransmux, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: wouldUseOriginal, hasher: &hasher)
  }

  public var description: String {
    return "EstimateMessage(outputBytes: \(String(describing: outputBytes)), durationMs: \(String(describing: durationMs)), widthPx: \(String(describing: widthPx)), heightPx: \(String(describing: heightPx)), wouldTransmux: \(String(describing: wouldTransmux)), wouldUseOriginal: \(String(describing: wouldUseOriginal)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AudioModeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return MediaInfoMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return CompressRequestMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return CompressResultMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return EstimateMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AudioModeMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? MediaInfoMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? CompressRequestMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? CompressResultMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? EstimateMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Reads media info from a file. Implemented on every platform in this phase.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ProbeHostApi {
  /// Returns the [MediaInfoMessage] for the media at [path].
  ///
  /// Declared here in full for the whole contract; only the Android implementation lands in
  /// this plan. Failures throw `CompressVideoError` with the [path] never logged or included
  /// in any diagnostic output outside the returned error detail.
  func getMediaInfo(path: String) async throws -> MediaInfoMessage
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ProbeHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ProbeHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ProbeHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Returns the [MediaInfoMessage] for the media at [path].
    ///
    /// Declared here in full for the whole contract; only the Android implementation lands in
    /// this plan. Failures throw `CompressVideoError` with the [path] never logged or included
    /// in any diagnostic output outside the returned error detail.
    let getMediaInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.compress_video.ProbeHostApi.getMediaInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMediaInfoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.getMediaInfo(path: pathArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getMediaInfoChannel.setMessageHandler(nil)
    }
  }
}
/// Generates poster-frame thumbnails from a file. Declared here for contract completeness;
/// no platform implements this yet — that lands in a later plan in this phase.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ThumbnailHostApi {
  /// Returns JPEG-encoded thumbnail bytes for the frame at [positionMs] in the media at
  /// [path], encoded at [quality] (1-100), with the longer side capped at [maxDimensionPx]
  /// when non-null (never upscaled).
  func getThumbnail(path: String, positionMs: Int64, quality: Int64, maxDimensionPx: Int64?) async throws -> FlutterStandardTypedData
  /// Same as [getThumbnail], but writes the JPEG to a file and returns its path. Writes to a
  /// unique name in the app cache directory, or to [outputPath] when given.
  func getThumbnailFile(path: String, positionMs: Int64, quality: Int64, maxDimensionPx: Int64?, outputPath: String?) async throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ThumbnailHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ThumbnailHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ThumbnailHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Returns JPEG-encoded thumbnail bytes for the frame at [positionMs] in the media at
    /// [path], encoded at [quality] (1-100), with the longer side capped at [maxDimensionPx]
    /// when non-null (never upscaled).
    let getThumbnailChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.compress_video.ThumbnailHostApi.getThumbnail\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getThumbnailChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let positionMsArg = args[1] as! Int64
        let qualityArg = args[2] as! Int64
        let maxDimensionPxArg: Int64? = nilOrValue(args[3])
        Task { @MainActor in
          do {
            let result = try await api.getThumbnail(path: pathArg, positionMs: positionMsArg, quality: qualityArg, maxDimensionPx: maxDimensionPxArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getThumbnailChannel.setMessageHandler(nil)
    }
    /// Same as [getThumbnail], but writes the JPEG to a file and returns its path. Writes to a
    /// unique name in the app cache directory, or to [outputPath] when given.
    let getThumbnailFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.compress_video.ThumbnailHostApi.getThumbnailFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getThumbnailFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let positionMsArg = args[1] as! Int64
        let qualityArg = args[2] as! Int64
        let maxDimensionPxArg: Int64? = nilOrValue(args[3])
        let outputPathArg: String? = nilOrValue(args[4])
        Task { @MainActor in
          do {
            let result = try await api.getThumbnailFile(path: pathArg, positionMs: positionMsArg, quality: qualityArg, maxDimensionPx: maxDimensionPxArg, outputPath: outputPathArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getThumbnailFileChannel.setMessageHandler(nil)
    }
  }
}
/// Runs and manages compression jobs. Implemented per-platform; this phase implements Android
/// only.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CompressHostApi {
  /// Starts a compression job for the media at [path], identified by the caller-generated
  /// [jobId], with the given [request]. [jobId] is generated by the caller (Dart) so two jobs
  /// started back to back never race on native-side id generation.
  func startCompress(path: String, jobId: String, request: CompressRequestMessage) async throws -> CompressResultMessage
  /// Cancels the job identified by [jobId]. A no-op if the job has already finished.
  func cancel(jobId: String) async throws
  /// Returns a pre-flight [EstimateMessage] for compressing the media at [path] with
  /// [request], without running an actual encode.
  func estimate(path: String, request: CompressRequestMessage) async throws -> EstimateMessage
  /// Deletes every file the plugin has written to its own cache directory.
  func clearCache() async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CompressHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `CompressHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CompressHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Starts a compression job for the media at [path], identified by the caller-generated
    /// [jobId], with the given [request]. [jobId] is generated by the caller (Dart) so two jobs
    /// started back to back never race on native-side id generation.
    let startCompressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.compress_video.CompressHostApi.startCompress\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startCompressChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let jobIdArg = args[1] as! String
        let requestArg = args[2] as! CompressRequestMessage
        Task { @MainActor in
          do {
            let result = try await api.startCompress(path: pathArg, jobId: jobIdArg, request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startCompressChannel.setMessageHandler(nil)
    }
    /// Cancels the job identified by [jobId]. A no-op if the job has already finished.
    let cancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.compress_video.CompressHostApi.cancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let jobIdArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.cancel(jobId: jobIdArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelChannel.setMessageHandler(nil)
    }
    /// Returns a pre-flight [EstimateMessage] for compressing the media at [path] with
    /// [request], without running an actual encode.
    let estimateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.compress_video.CompressHostApi.estimate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      estimateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let requestArg = args[1] as! CompressRequestMessage
        Task { @MainActor in
          do {
            let result = try await api.estimate(path: pathArg, request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      estimateChannel.setMessageHandler(nil)
    }
    /// Deletes every file the plugin has written to its own cache directory.
    let clearCacheChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.compress_video.CompressHostApi.clearCache\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearCacheChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.clearCache()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearCacheChannel.setMessageHandler(nil)
    }
  }
}

/// Progress notifications from native code back to Dart, keyed by job id. Fire-and-forget:
/// Dart does not reply to this call.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol CompressVideoFlutterApiProtocol {
  /// Reports that the job identified by [jobId] has reached [percent] (0 to 100) complete.
  @MainActor func onProgress(jobId jobIdArg: String, percent percentArg: Double) async throws
}
class CompressVideoFlutterApi: CompressVideoFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  /// Reports that the job identified by [jobId] has reached [percent] (0 to 100) complete.
  @MainActor func onProgress(jobId jobIdArg: String, percent percentArg: Double) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.compress_video.CompressVideoFlutterApi.onProgress\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([jobIdArg, percentArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: CompressVideoError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
